// Dataset pour la génération de faux profils et de faux commentaires (engagement ghost admin)

export const firstNames = [
  'James', 'Mary', 'John', 'Patricia', 'Robert', 'Jennifer', 'Michael', 'Linda',
  'William', 'Barbara', 'David', 'Elizabeth', 'Richard', 'Susan', 'Joseph', 'Jessica',
  'Thomas', 'Sarah', 'Charles', 'Karen', 'Christopher', 'Lisa', 'Daniel', 'Nancy',
  'Matthew', 'Betty', 'Anthony', 'Margaret', 'Mark', 'Sandra', 'Donald', 'Ashley',
  'Steven', 'Dorothy', 'Paul', 'Kimberly', 'Andrew', 'Emily', 'Joshua', 'Donna',
  'Kenneth', 'Michelle', 'Kevin', 'Carol', 'Brian', 'Amanda', 'George', 'Melissa',
  'Timothy', 'Deborah', 'Ronald', 'Stephanie', 'Edward', 'Rebecca', 'Jason', 'Sharon',
  'Jeffrey', 'Laura', 'Ryan', 'Cynthia', 'Jacob', 'Kathleen', 'Gary', 'Amy',
  'Nicholas', 'Angela', 'Eric', 'Shirley', 'Jonathan', 'Anna', 'Stephen', 'Brenda',
  'Larry', 'Pamela', 'Justin', 'Emma', 'Scott', 'Nicole', 'Brandon', 'Helen',
  'Benjamin', 'Samantha', 'Samuel', 'Katherine', 'Gregory', 'Christine', 'Alexander', 'Debra',
  'Frank', 'Rachel', 'Patrick', 'Carolyn', 'Raymond', 'Janet', 'Jack', 'Catherine',
  'Dennis', 'Maria', 'Jerry', 'Heather', 'Tyler', 'Diane', 'Aaron', 'Ruth',
  'Jose', 'Julie', 'Adam', 'Olivia', 'Nathan', 'Joyce', 'Henry', 'Virginia',
  'Douglas', 'Victoria', 'Zachary', 'Kelly', 'Peter', 'Lauren', 'Kyle', 'Christina',
  'Noah', 'Joan', 'Ethan', 'Evelyn', 'Jeremy', 'Judith', 'Walter', 'Megan',
  'Christian', 'Andrea', 'Keith', 'Cheryl', 'Roger', 'Hannah', 'Terry', 'Jacqueline',
  'Austin', 'Martha', 'Sean', 'Gloria', 'Gerald', 'Teresa', 'Carl', 'Ann',
  'Harold', 'Sara', 'Dylan', 'Madison', 'Arthur', 'Frances', 'Lawrence', 'Kathryn',
  'Jordan', 'Janice', 'Jesse', 'Jean', 'Bryan', 'Abigail', 'Billy', 'Alice',
  'Bruce', 'Judy', 'Gabriel', 'Sophia', 'Joe', 'Grace', 'Logan', 'Denise',
  'Albert', 'Amber', 'Willie', 'Doris', 'Alan', 'Marilyn', 'Eugene', 'Danielle',
  'Russell', 'Beverly', 'Vincent', 'Isabella', 'Philip', 'Theresa', 'Bobby', 'Diana',
  'Johnny', 'Natalie', 'Bradley', 'Brittany', 'Roy', 'Charlotte', 'Ralph', 'Marie',
  'Louis', 'Kayla', 'Randy', 'Alexis', 'Howard', 'Lori',
]

export const lastNames = [
  'Smith', 'Johnson', 'Williams', 'Brown', 'Jones', 'Garcia', 'Miller', 'Davis',
  'Rodriguez', 'Martinez', 'Hernandez', 'Lopez', 'Gonzalez', 'Wilson', 'Anderson',
  'Thomas', 'Taylor', 'Moore', 'Jackson', 'Martin', 'Lee', 'Perez', 'Thompson',
  'White', 'Harris', 'Sanchez', 'Clark', 'Ramirez', 'Lewis', 'Robinson', 'Walker',
  'Young', 'Allen', 'King', 'Wright', 'Scott', 'Torres', 'Nguyen', 'Hill',
  'Flores', 'Green', 'Adams', 'Nelson', 'Baker', 'Hall', 'Rivera', 'Campbell',
  'Mitchell', 'Carter', 'Roberts', 'Evans', 'Turner', 'Phillips', 'Parker', 'Collins',
  'Edwards', 'Stewart', 'Morris', 'Morales', 'Murphy', 'Cook', 'Rogers', 'Gutierrez',
  'Ortiz', 'Morgan', 'Cooper', 'Peterson', 'Bailey', 'Reed', 'Kelly', 'Howard',
  'Ramos', 'Kim', 'Cox', 'Ward', 'Richardson', 'Watson', 'Brooks', 'Chavez',
  'Wood', 'James', 'Bennett', 'Gray', 'Mendoza', 'Ruiz', 'Hughes', 'Price',
  'Alvarez', 'Castillo', 'Sanders', 'Patel', 'Myers', 'Long', 'Ross', 'Foster',
  'Jimenez', 'Powell', 'Jenkins', 'Perry', 'Russell', 'Sullivan', 'Bell', 'Coleman',
  'Butler', 'Henderson', 'Barnes', 'Gonzales', 'Fisher', 'Vasquez', 'Simmons', 'Graham',
  'Murray', 'Ford', 'Hamilton', 'Griffin', 'Wallace', 'Moreno', 'West', 'Cole',
  'Hayes', 'Bryant', 'Herrera', 'Gibson', 'Ellis', 'Tran', 'Medina', 'Aguilar',
  'Stevens', 'Murray', 'Ford', 'Marshall', 'Owens', 'Harrison', 'Fernandez', 'McDonald',
  'Woods', 'Washington', 'Kennedy', 'Wells', 'Vargas', 'Henry', 'Chen', 'Freeman',
  'Webb', 'Tucker', 'Guzman', 'Burns', 'Crawford', 'Olson', 'Simpson', 'Porter',
  'Hunter', 'Gordon', 'Mendez', 'Silva', 'Shaw', 'Snyder', 'Mason', 'Dixon',
  'Munoz', 'Hunt', 'Hicks', 'Holmes', 'Palmer', 'Wagner', 'Black', 'Robertson',
  'Boyd', 'Rose', 'Stone', 'Salazar', 'Fox', 'Warren', 'Mills', 'Meyer',
  'Rice', 'Schmidt', 'Garza', 'Daniels', 'Ferguson', 'Nichols', 'Stephens', 'Soto',
]

const usedUsernames = new Set()

export function generateFakeName() {
  const first = firstNames[Math.floor(Math.random() * firstNames.length)]
  const last = lastNames[Math.floor(Math.random() * lastNames.length)]
  const displayName = `${first} ${last}`

  let username
  let attempts = 0
  do {
    const suffix = Math.floor(Math.random() * 9999)
    username = `${first.toLowerCase()}${last.toLowerCase()}${suffix}`
    attempts++
  } while (usedUsernames.has(username) && attempts < 20)

  usedUsernames.add(username)
  return { displayName, username }
}

export const moods = [
  { value: 'joyeux', label: 'Joyeux 😄' },
  { value: 'en_colere', label: 'En colère 😡' },
  { value: 'triste', label: 'Triste 😢' },
  { value: 'excite', label: 'Excité 🤩' },
  { value: 'choque', label: 'Choqué 😱' },
  { value: 'indifferent', label: 'Indifférent 😐' },
  { value: 'amoureux', label: 'Amoureux 🥰' },
]

export const moodPhrases = {
  joyeux: [
    "J'adore !!!",
    "Trop bien !",
    "Super contente !",
    "Ça m'a fait sourire ❤️",
    "Magnifique !",
    "Waou, j'adore vraiment !",
    "Tellement positif, merci !",
    "Ça fait du bien de voir ça !",
    "Parfait !",
    "Génial !!!",
    "C'est exactement ce qu'il fallait !",
    "Vous êtes les meilleurs !",
    "On en voulait encore !",
    "5 étoiles 🌟",
    "Bravo à toute l'équipe !",
    "Je souris en lisant ça !",
    "Trop beau 😍",
    "Franchement super !",
    "Que du bonheur !",
    "Je partage à tout le monde !",
    "Ça fait plaisir à voir !",
    "Merci pour cette bonne nouvelle !",
    "YES ! J'attendais ça !",
    "C'est tout ce que j'espérais !",
    "Ça met du baume au cœur 😊",
    "Bravo, vraiment bravo !",
    "Top, top, top !",
    "Tellement content(e) !",
    "Grande nouvelle !",
    "On aime, on valide ✅",
    "Rien à dire, c'est parfait.",
    "Ça me rend happy !",
    "Je kiffe trop 😄",
    "Quelle bonne surprise !",
    "J'ai le sourire jusqu'aux oreilles !",
    "Trop fière de vous !",
    "Je recommande à 200% !",
    "Vous gérez !",
    "C'est du lourd !",
    "Un grand merci pour ça !",
    "Exactement ce qu'il nous fallait ❤️",
    "La meilleure chose que j'ai vue aujourd'hui !",
    "Je suis aux anges !",
    "Wow, impressionnant !",
    "Ça donne la pêche !",
    "Plus que parfait 👏",
    "J'en redemande !",
    "C'est une pépite !",
    "Incroyable, j'adore !",
    "Vous avez fait ma journée !",
    "Hâte de voir la suite !",
    "Le meilleur contenu possible !",
    "Ça fait chaud au cœur 🥰",
    "Formidable !",
    "On veut plus de ça !",
    "Chapeau bas 🎩",
    "Je suis fan !",
    "C'est beau, c'est bon, c'est parfait.",
    "Continue comme ça !",
    "Pure merveille !",
    "J'en pleure de joie presque 😂",
    "Quel plaisir de lire ça !",
    "Ça vaut de l'or !",
    "Merci infiniment !",
    "Top qualité comme toujours !",
    "Je like, je commente, je partage !",
    "Le bonheur à l'état pur.",
    "C'est la joie totale ici !",
    "Waouh, je suis bluffé(e) !",
    "J'adore ce genre de post !",
    "Pur bonheur 🌈",
    "Tout simplement magnifique !",
    "Ça change la vie !",
    "Mon post préféré de la journée !",
    "Bravo les gars ! 🎉",
    "On est gâtés !",
    "Ça c'est du contenu de qualité !",
    "Mille mercis !",
    "Enfin une bonne nouvelle 😄",
    "J'adore, point final.",
    "Respect total !",
    "Je valide à fond !",
    "Trop chouette !",
    "C'est la classe !",
    "Un pur régal !",
    "J'applaudis des deux mains 👏👏",
    "Superbe travail !",
    "J'ai le cœur qui fait boom !",
    "C'est du génie !",
    "Meilleur post ever !",
    "Je suis comblé(e) !",
    "Ça rend heureux !",
    "Trop cool !!!",
    "J'en veux encore !",
    "C'est magnifiquement bien fait !",
    "Splendide !",
    "On est bénis 🙏",
    "Je souris bêtement devant mon écran.",
    "C'est tout simplement incroyable !",
    "Quel chef-d'œuvre !",
  ],
  en_colere: [
    "C'est trop !",
    "Ils se foutent de notre gueule !",
    "Scandaleux !!!",
    "Inacceptable.",
    "J'en reviens pas...",
    "C'est une honte !",
    "On ne mérite pas ça !",
    "Sérieusement ?!",
    "Révoltant.",
    "Pourquoi ??? 😤",
    "Ça suffit maintenant !",
    "Je suis hors de moi.",
    "Non mais ils se prennent pour qui ?",
    "Stop avec ces conneries !",
    "Je suis dégoûté(e).",
    "Boycott !",
    "Vous nous prenez vraiment pour des idiots.",
    "Inadmissible !!!",
    "J'aurais jamais cru ça possible.",
    "Complètement hors sujet.",
    "C'est n'importe quoi !",
    "Ras-le-bol !!!",
    "On va pas se laisser faire !",
    "Honteux.",
    "Je suis furieux/furieuse.",
    "Et on devrait dire merci en plus ?",
    "On marche sur la tête.",
    "C'est inadmissible de faire ça.",
    "Je ne pardonne pas ça.",
    "C'est la goutte de trop.",
    "Vous avez perdu tout crédit.",
    "Plus JAMAIS.",
    "Faut arrêter de nous mentir.",
    "C'est du foutage de gueule pur et simple.",
    "J'ai la rage là.",
    "Non mais sérieux ???",
    "On aura tout vu.",
    "Je suis écœuré(e).",
    "Zéro respect.",
    "Tout ça pour ça ?!",
    "Vous vous foutez du monde.",
    "Comment osez-vous ?",
    "C'est une insulte.",
    "Je ne recommande plus RIEN.",
    "Y'a des limites quand même !",
    "C'est lamentable.",
    "Quelle arnaque !",
    "Je suis révolté(e).",
    "Aucune excuse possible.",
    "C'est du mépris total.",
    "STOP.",
    "C'est la fin pour moi.",
    "Vous avez ruiné tout.",
    "Pathétique.",
    "C'est du vol.",
    "Je ne supporte plus ça.",
    "On se moque de qui là ?",
    "C'est irrespectueux.",
    "Je perds patience.",
    "Honte à vous.",
    "Rendez-nous des comptes !",
    "Plus aucune confiance.",
    "La colère est légitime.",
    "C'est indigne.",
    "Vous cassez tout.",
    "J'en ai marre de cette situation.",
    "C'est insupportable.",
    "On était prévenus mais quand même...",
    "Zéro. Zéro sur toute la ligne.",
    "C'est la honte internationale.",
    "Je regrette d'avoir fait confiance.",
    "Coup de gueule mérité.",
    "C'est lamentable de A à Z.",
    "Indignation totale.",
    "Comment on en est arrivé là ?",
    "C'est la pire chose que j'ai vue.",
    "Je suis vert(e) de rage.",
    "Ça me met dans une colère noire.",
    "Non mais allô quoi ?!",
    "Faut que ça change MAINTENANT.",
    "Incompétence totale.",
    "On touche le fond là.",
    "Y'en a marre à la fin !",
    "C'est abusé.",
    "C'est une trahison.",
    "Je demande des explications.",
    "C'est du délire complet.",
    "J'appelle au boycott.",
    "Virez les responsables !",
    "C'est tout bonnement inadmissible.",
    "Mon sang ne fait qu'un tour.",
    "Quelle blague...",
    "Je fulmine.",
    "C'est pas possible d'être aussi nuls.",
    "La coupe est pleine.",
    "Je ne laisserai pas passer ça.",
    "C'est criminel.",
    "On nous a menti !",
    "Où est la décence ?",
    "J'ai la haine.",
    "C'est la pire décision jamais prise.",
  ],
  triste: [
    "Ça m'a brisé le cœur.",
    "Je suis dévastée...",
    "Trop triste 😢",
    "Je pleure en lisant ça.",
    "C'est tellement douloureux.",
    "Pourquoi les choses doivent être comme ça ?",
    "Je me sens si seule face à ça.",
    "Mon cœur saigne.",
    "Je pensais que ça irait mieux.",
    "C'est dur à accepter.",
    "Personne ne mérite ça.",
    "Ça me rappelle des moments difficiles.",
    "Je vous envoie plein de force 💙",
    "Je préfère ne pas y penser.",
    "Tellement injuste.",
    "Mes pensées vous accompagnent.",
    "On sera là pour vous.",
    "Restez forts.",
    "Je vous soutiens de tout cœur.",
    "C'est une vraie peine.",
    "J'ai le cœur lourd.",
    "Ça me rend tellement triste.",
    "Je suis au bord des larmes.",
    "Quel dommage...",
    "La vie est cruelle parfois.",
    "Je ne m'en remets pas.",
    "C'est un crève-cœur.",
    "Tellement de peine...",
    "Je n'arrive pas à y croire.",
    "Ça fait si mal.",
    "J'aimerais pouvoir changer les choses.",
    "Je suis anéanti(e).",
    "C'est déchirant.",
    "Mon cœur est en miettes.",
    "Comment surmonter ça ?",
    "Je pense à vous très fort 💙",
    "C'est la nouvelle la plus triste.",
    "J'ai du mal à respirer en lisant ça.",
    "Courage à tous.",
    "C'est bouleversant.",
    "Je suis en deuil.",
    "Pourquoi maintenant...",
    "Ça ne devrait pas arriver.",
    "Je suis effondrée.",
    "La tristesse m'envahit.",
    "C'est trop cruel.",
    "Je pleure pour eux.",
    "Tellement de chagrin.",
    "La douleur est immense.",
    "Je ne sais pas quoi dire à part... tristesse.",
    "Je vous embrasse fort.",
    "Prenez soin de vous 🫂",
    "C'est un cauchemar.",
    "J'ai le moral à zéro.",
    "Ça ne sera plus jamais pareil.",
    "Je suis sans force.",
    "C'est une immense perte.",
    "Tout s'effondre.",
    "Je garde espoir malgré tout...",
    "C'est si douloureux de lire ça.",
    "Je n'ai plus les mots.",
    "Mon âme pleure.",
    "On ne s'en remet jamais complètement.",
    "C'est le genre de nouvelle qui détruit.",
    "La page la plus triste que j'ai lue.",
    "Je suis tellement désolé(e).",
    "Ça me déchire de l'intérieur.",
    "Mes yeux sont rouges.",
    "Comment continuer après ça ?",
    "Je vous porte dans mes prières.",
    "Un immense vide.",
    "Le monde est injuste.",
    "C'est insoutenable.",
    "Je voudrais tellement aider.",
    "Un bout de moi s'est brisé.",
    "RIP... 🕊️",
    "C'est dévastateur.",
    "Je garderai toujours ce souvenir.",
    "Les larmes coulent toutes seules.",
    "C'est un adieu trop tôt.",
    "Trop jeune pour ça.",
    "La vie ne tient à rien.",
    "Mon cœur va exploser de tristesse.",
    "Que c'est dur...",
    "J'aurais voulu que ça se passe autrement.",
    "On ne méritait pas ça.",
    "C'est la fin d'une époque 😢",
    "Je vous aime, restez forts.",
    "Plein de courage et d'amour.",
    "C'est tellement vide sans...",
    "Je suis inconsolable.",
    "Rien ne pourra effacer cette peine.",
    "C'est un chagrin immense.",
    "Je tremble en lisant ces mots.",
    "Adieu... tu vas nous manquer.",
    "Chaque mot me fait pleurer.",
    "Le silence est la seule réponse.",
    "Ce monde peut être si cruel.",
    "Je suis avec vous par la pensée.",
    "Accrochez-vous.",
    "Merci d'en avoir parlé. 💙",
  ],
  excite: [
    "OMGGGG !!!",
    "J'en reviens pas !!!",
    "INCROYABLE !!!",
    "C'est dingue !!!",
    "YESSS !!!",
    "Je suis TROP excité(e) !!",
    "Ça y est !!!!! 🎉",
    "JE CRIE !!!",
    "Ma journée est faite !!",
    "ENFIN !!!",
    "C'est OFFICIAL ??",
    "Mon Dieu je tremble !!!",
    "JE SAVAIS QUE ÇA ALLAIT ARRIVER !!!",
    "Vivement la suite !!!!!",
    "On est les premiers à savoir !!",
    "TROP TOP !!",
    "Je peux pas y croire ???",
    "OMG OMG OMG",
    "C'est le meilleur jour de ma vie.",
    "Je danse de joie là 🕺",
    "AAAAAAH !!!",
    "C'est réel ?? Dites-moi que c'est réel !",
    "Je fais le tour de la maison en courant !!!",
    "LE FEU 🔥🔥🔥",
    "J'ai les mains qui tremblent !!!",
    "INCROYABLE DE OUF !!!",
    "JE HURLE DE JOIE !!!!",
    "Mes voisins vont me détester tellement je crie !!",
    "C'est confirmé ???? OMG !!!",
    "JE SUIS EN PLS DE BONHEUR !!!",
    "ENFIN ENFIN ENFIN !!!",
    "Ça va être LÉGENDAIRE !!!",
    "JE PLEURE DE JOIE !!!",
    "OMG mon cœur bat à 200 !!",
    "C'est le moment qu'on attendait !!!",
    "TAKE MY MONEY !!!",
    "Je peux mourir en paix maintenant.",
    "YOOOO !!!",
    "JE SUIS HYPÉ AU MAX !!!",
    "C'est Noël avant l'heure !!!",
    "J'en ai la chair de poule !!!!",
    "MAIS C'EST ÉNORME !!!",
    "OK JE PERDS LA TÊTE !!",
    "Let's GOOOO 🚀🚀🚀",
    "Mon cerveau explose !!!",
    "JE VAIS EXPLOSER !!!",
    "C'EST HISTORIQUE !!!",
    "On va en parler pendant DES ANNÉES !!",
    "CHAMPAGNE 🍾🍾🍾",
    "Je savais que ce jour viendrait !!!",
    "WHO'S HYPED ?? MOI !!!",
    "Mes jambes tremblent de joie !!!",
    "C'EST LA FOLIIIIE !!!",
    "BEST. DAY. EVER.",
    "Je suis en lévitation là !!",
    "AHHHHHHH TROP BIEN !!!!!",
    "C'est parti !!! On lâche rien !",
    "Le hype train est lancé 🚂💨",
    "Je suis SUR UN NUAGE !!!",
    "RIEN NE PEUT ARRÊTER ÇA !!!",
    "C'est le plus beau jour !!",
    "OK j'appelle tout le monde immédiatement.",
    "J'AI CRIÉ DANS LE MÉTRO !!",
    "La hype est réelle !!!!",
    "J'en ai les larmes aux yeux de joie !!!",
    "JE TOMBE DE MA CHAISE !!",
    "C'est du LOURD DE LOURD !!!",
    "Mon téléphone vibre tellement j'ai de notifs !!!",
    "C'est le délire total !!!",
    "WOW WOW WOW !!!",
    "Ça dépasse tous mes rêves !!!",
    "JE SUIS PRÊT(E) !!!",
    "C'est magique !!!",
    "QUELLE ANNONCE !!! 🤯",
    "Je pose ma dem' pour vivre ce moment !!",
    "MON CŒUR 💖💖💖",
    "Rien de mieux, jamais.",
    "FESTIVAL DE JOIE !!!",
    "Je. Suis. Mort(e). De bonheur.",
    "Allez, on célèbre !! 🎊",
    "GROS GROS GROS !!!",
    "Tout le monde debout !!!",
    "C'EST LE MOMENT !!!",
    "Je suis en sueur d'excitation !!",
    "FABULEUX !!!",
    "C'est au-delà de ce que j'imaginais !!!",
    "GO GO GO !!!",
    "J'ai le plus grand sourire du monde !!",
    "Ça va être une TUERIE !!!",
    "WAKE UP EVERYBODY !!!",
    "BREAKING NEWS ET JE SUIS LÀ POUR ÇA !!",
    "Je veux être le premier à le dire : BRAVO !!!",
    "C'est tout ce que j'ai toujours voulu !!!",
    "JE MEURS (de joie) !!!",
    "PAS POSSIBLE !!!!! SI ???",
    "C'est mieux que dans mes rêves !!!!",
    "ON EST VIVANTS ET C'EST MAGNIFIQUE !!!",
    "RÉALITÉ OU RÊVE ??? 😍",
    "J'ai des frissons partout !!!",
    "C'est officiel, je suis le/la plus heureux/se !",
    "BOOM 💥💥💥",
  ],
  choque: [
    "Quoi ?!",
    "Sérieusement ?!",
    "Je suis sans voix.",
    "Impossible...",
    "Non. Non non non.",
    "Attendez, c'est réel ?",
    "Je n'aurais jamais imaginé ça.",
    "C'est une blague ?",
    "Choqué(e) à 100%.",
    "Je dois relire ça plusieurs fois.",
    "Mes yeux me trompent.",
    "C'est du grand n'importe quoi.",
    "Comment est-ce possible ?",
    "J'hallucine complètement.",
    "Ça dépasse l'entendement.",
    "Je suis bouche bée.",
    "On nage en plein délire.",
    "Pardon ??",
    "Je ne sais pas quoi dire.",
    "C'est… inattendu.",
    "WHAT ???",
    "C'est réel ça ??",
    "Je cligne des yeux et je relis.",
    "Non mais c'est un rêve ?",
    "Je tombe des nues.",
    "Mon cerveau a planté.",
    "Ça m'a coupé les jambes.",
    "C'est quoi ce délire ?",
    "Le sol s'effondre sous mes pieds.",
    "Je n'en crois pas mes yeux.",
    "C'est irréel.",
    "Mon menton est au sol.",
    "Attendez… QUOI ?",
    "Je relis pour la 5e fois.",
    "C'est le retournement de situation du siècle.",
    "J'ai fait tomber mon téléphone.",
    "C'est un plot twist digne d'un film.",
    "J'ai la mâchoire qui se décroche.",
    "C'est véritablement choquant.",
    "Je reste figé(e).",
    "Mais… mais… comment ?!",
    "C'est surréaliste.",
    "Vous rigolez j'espère ?",
    "OK j'ai besoin d'une pause.",
    "Absolument choquant.",
    "Je. Suis. Sous. Le. Choc.",
    "C'est la chose la plus inattendue.",
    "Mon monde vient de basculer.",
    "Hein ??!",
    "C'est pas vrai…",
    "Attendez une minute là.",
    "Je crois que mon cœur s'est arrêté.",
    "C'est du jamais vu.",
    "WOW... juste WOW.",
    "Quelqu'un peut m'expliquer ?",
    "C'est la définition même du choc.",
    "Non mais COMMENT ?",
    "Je tremblote en lisant ça.",
    "C'est le monde à l'envers.",
    "Je ne m'y attendais absolument pas.",
    "C'est un coup de tonnerre.",
    "Invraisemblable.",
    "Je croyais que c'était fake.",
    "Je suis paralysé(e).",
    "Ça change tout.",
    "C'est un séisme.",
    "Je suis abasourdi(e).",
    "Je refuse d'y croire.",
    "Même dans un film on n'oserait pas.",
    "C'est la réalité ??? Pour de vrai ???",
    "J'ai dû relire 3 fois.",
    "Je suis médusé(e).",
    "C'est lunaire.",
    "On est dans la 4e dimension.",
    "Le retournement qu'on n'a pas vu venir.",
    "C'est dément.",
    "Mon corps entier est en mode freeze.",
    "C'est vertigineux.",
    "Je n'ai plus les mots.",
    "C'est de la science-fiction là.",
    "Ma tête va exploser.",
    "C'est un cauchemar éveillé.",
    "Tout ce que je savais est faux.",
    "J'ai perdu la parole.",
    "Je vais m'asseoir 2 minutes.",
    "J'en suis resté(e) figé(e) 10 minutes.",
    "C'est un tremblement de terre émotionnel.",
    "Pincez-moi je rêve.",
    "Je crois que j'ai un bug.",
    "Quelqu'un confirme SVP ??",
    "C'est le genre de truc qu'on n'oublie pas.",
    "C'est comme un uppercut.",
    "J'en ai le vertige.",
    "Je ne réalise pas encore.",
    "Il me faut du temps pour digérer ça.",
    "C'est la claque de l'année.",
    "J'ai le souffle coupé.",
    "Je suis en état de choc total.",
    "On ne s'attendait VRAIMENT pas à ça.",
    "C'est la bombe du siècle.",
    "Je n'arrive pas à traiter l'information.",
  ],
  indifferent: [
    "Mouais.",
    "Bof.",
    "Pas vraiment surpris.",
    "Et alors ?",
    "Ok.",
    "Rien de nouveau sous le soleil.",
    "C'est déjà vu.",
    "Sans commentaire.",
    "Peu importe.",
    "Je m'en fiche un peu.",
    "Ça ne change rien pour moi.",
    "Comme d'habitude.",
    "Ni bien ni mal.",
    "J'avais prévu ça.",
    "On verra bien.",
    "Pourquoi pas.",
    "Je reste neutre là-dessus.",
    "Ça ne m'étonne pas.",
    "Classique.",
    "Bon.",
    "Ouais, et ?",
    "Cool.",
    "Si vous le dites.",
    "C'est une info comme une autre.",
    "Je prends note.",
    "D'accord.",
    "Hmm.",
    "Pas de quoi fouetter un chat.",
    "Je passe.",
    "Pas mon problème.",
    "C'est noté.",
    "OK, next.",
    "Ah bon.",
    "Je ne vois pas l'intérêt.",
    "Rien d'exceptionnel.",
    "Bah.",
    "Pas ouf.",
    "C'était prévisible.",
    "Ça m'est égal.",
    "Aucun avis.",
    "Neutre.",
    "Je scroll.",
    "M'en fous.",
    "Pas concerné(e).",
    "Ça ne me touche pas plus que ça.",
    "Meh.",
    "Zéro émotion.",
    "C'est normal non ?",
    "Ça arrive.",
    "Logique.",
    "Je n'ai pas d'opinion.",
    "C'est possible oui.",
    "Vu.",
    "Pas de réaction particulière.",
    "C'est pas si grave.",
    "On a vu pire.",
    "Ça ne mérite pas le buzz.",
    "Tant mieux ou tant pis.",
    "Je ne sais pas quoi en penser.",
    "C'est du tiède.",
    "Un jour de plus.",
    "Sympa mais sans plus.",
    "Je n'attendais rien, je ne suis pas déçu(e).",
    "Euh... ok ?",
    "C'est pas le scoop du siècle non plus.",
    "Ça se vaut.",
    "Je hausse les épaules.",
    "Ni pour ni contre.",
    "C'est un avis.",
    "Bon, et la suite ?",
    "Je suis mitigé(e).",
    "Ça me laisse de marbre.",
    "On va pas en faire tout un plat.",
    "C'est juste... normal ?",
    "Banalité.",
    "Je n'ai rien à ajouter.",
    "Ça existe, oui.",
    "Je n'ai pas d'émotion là-dessus.",
    "J'ai vu, j'ai scrollé.",
    "Ça va, ça vient.",
    "On s'en remettra.",
    "Tant pis.",
    "Pas passionnant.",
    "Voilà voilà.",
    "C'est la vie.",
    "Bref.",
    "Je retiens pas.",
    "C'est du vent.",
    "À voir.",
    "Rien de plus à dire.",
    "Possible.",
    "Pas impressionné(e).",
    "Whatever.",
    "Next.",
    "Bon ben voilà quoi.",
    "C'est pas pour moi.",
    "Je suis spectateur/spectatrice.",
    "Pas d'avis tranché.",
    "Je laisse passer.",
    "Pas transcendant.",
  ],
  amoureux: [
    "Tellement beau ❤️",
    "Je t'aime trop",
    "Mon cœur 🥺",
    "Trop mignon(ne) !",
    "❤️❤️❤️",
    "Je vous adore.",
    "C'est tellement touchant.",
    "L'amour existe encore !",
    "Ça réchauffe le cœur.",
    "Vous êtes magnifiques.",
    "Je suis émue aux larmes ❤️",
    "De la beauté pure.",
    "Ça donne de l'espoir.",
    "Vous êtes faits l'un pour l'autre.",
    "Trop cute !!",
    "Je veux la même chose 😭❤️",
    "On fond devant ça.",
    "Le bonheur ça ressemble à ça.",
    "Trop d'amour pour ce post.",
    "Mes yeux brillent 🌟",
    "Vous êtes mon couple préféré !",
    "Ça me fait croire en l'amour 💕",
    "Mon cœur fond littéralement.",
    "L'amour avec un grand A !",
    "Je pleure de bonheur en voyant ça.",
    "C'est trop beau pour être vrai 😍",
    "Couple goals !!!",
    "Je suis en larmes (de joie) 😭❤️",
    "Ça c'est de l'amour, du vrai !",
    "Protégez-les à tout prix 🛡️❤️",
    "Le monde a besoin de plus d'amour comme ça.",
    "Tellement adorable !",
    "Ça me donne des papillons dans le ventre 🦋",
    "Vous êtes la preuve que l'amour existe.",
    "OTP (One True Pairing) !!!",
    "J'en ai des frissons d'émotion.",
    "Mon cœur est plein à craquer.",
    "C'est le plus beau message que j'ai lu ❤️",
    "Je vous souhaite tout le bonheur du monde.",
    "C'est de la pure tendresse.",
    "Ça donne envie d'aimer !",
    "Trop chou 🥰",
    "Je suis en mode guimauve devant mon écran.",
    "Le post le plus wholesome !",
    "Je shippppp tellement !!!",
    "Des étoiles dans les yeux ✨",
    "C'est magique ce que vous avez.",
    "L'amour inconditionnel ça ressemble à ça.",
    "Tellement de tendresse dans ce post.",
    "Je vais pleurer 😭❤️",
    "C'est la plus belle chose du jour.",
    "Vous méritez tout le bonheur.",
    "Ça me rend tout(e) chose.",
    "Forever and always ❤️",
    "C'est le genre de post qui restore ta foi en l'humanité.",
    "Mon cœur fait boum boum 💓",
    "C'est tellement pur.",
    "Je veux crier d'amour !",
    "Soulmates !!!",
    "Ça me fait fondre de l'intérieur.",
    "Trop beaux tous les deux 😍",
    "L'amour pur et simple.",
    "Je fonds comme du chocolat au soleil 🫠❤️",
    "C'est le post le plus mignon EVER.",
    "La vie est belle quand on voit ça.",
    "Je suis jalouse (mais en bien) 🥹",
    "Ça me donne la foi en l'amour.",
    "C'est un conte de fées moderne.",
    "Longue vie à vous deux !",
    "Tellement d'amour dans cette photo !",
    "AAAAAW 🥺🥺🥺",
    "C'est le genre de post qui me fait sourire instantanément.",
    "Vous irradiez de bonheur !",
    "C'est beau, c'est pur, c'est vrai.",
    "Love love love ❤️❤️❤️",
    "Ça devrait être illégal d'être aussi mignons.",
    "Mon feed a besoin de plus de ça.",
    "Trop de feels 😭💕",
    "C'est de l'or en barre.",
    "Vous êtes parfaits ensemble.",
    "Stop j'en peux plus c'est trop beau 😍",
    "C'est la définition du bonheur.",
    "Ça guérit tous mes problèmes.",
    "Je bookmark ce post pour toujours.",
    "Best couple !!!",
    "Mon cœur déborde ❤️",
    "Tellement chanceux/chanceuse !",
    "C'est l'amour avec un grand A majuscule.",
    "Je verse ma petite larme.",
    "C'est si beau que ça fait mal au cœur.",
    "L'amour brille à travers chaque mot.",
    "Gardez cet amour pour toujours.",
    "Plus beau que dans les films.",
    "🥺❤️ c'est tout ce que j'ai à dire.",
    "Cet amour me redonne espoir.",
    "C'est d'une beauté rare.",
    "Chaque mot transpire l'amour.",
    "Trop d'émotions pour un seul post.",
    "Vous êtes une source d'inspiration ❤️",
    "Le plus beau duo du monde.",
    "J'ai des étoiles plein les yeux grâce à vous 🌟",
  ],
}

export function getRandomPhrase(mood) {
  const phrases = moodPhrases[mood]
  if (!phrases || phrases.length === 0) return "..."
  return phrases[Math.floor(Math.random() * phrases.length)]
}
