<template>
  <div class="updates-page">
    <div class="up-header">
      <button @click="$router.back()" class="back-btn">&larr; Retour</button>
      <div class="up-tabs">
        <button class="up-tab" :class="{ active: tab === 'highlights' }" @click="tab = 'highlights'">Highlights</button>
        <button class="up-tab" :class="{ active: tab === 'patchnotes' }" @click="tab = 'patchnotes'">Patch Notes</button>
      </div>
    </div>

    <!-- ============ HIGHLIGHTS TIMELINE ============ -->
    <div v-if="tab === 'highlights'" class="hl-container">
      <div class="hl-intro">
        <h2 class="hl-intro-title">L'histoire d'iCAN</h2>
        <p class="hl-intro-sub">Chaque grande fonctionnalit&eacute; qui a façonn&eacute; le r&eacute;seau, du premier post aux groupes DM.</p>
      </div>

      <div class="hl-timeline">
        <div class="hl-line"></div>

        <div
          v-for="(item, i) in highlights"
          :key="i"
          class="hl-item"
          :class="{ right: i % 2 === 1 }"
        >
          <div class="hl-dot" :style="{ background: item.color }"></div>
          <div class="hl-card">
            <div class="hl-card-icon" :style="{ background: item.color + '20', color: item.color }">{{ item.icon }}</div>
            <div class="hl-card-content">
              <span class="hl-card-version">v{{ item.version }}</span>
              <span class="hl-card-date">{{ item.date }}</span>
              <h3 class="hl-card-title">{{ item.title }}</h3>
              <p class="hl-card-desc">{{ item.description }}</p>
              <div class="hl-card-tags">
                <span v-for="(tag, j) in item.tags" :key="j" class="hl-tag" :style="{ background: item.color + '20', color: item.color }">{{ tag }}</span>
              </div>
            </div>
          </div>
        </div>

        <div class="hl-item hl-start">
          <div class="hl-dot" style="background: var(--accent)"></div>
          <div class="hl-card hl-card-start">
            <div class="hl-card-icon" style="background: rgba(29, 161, 242, 0.2); color: var(--accent)">&#x1F680;</div>
            <div class="hl-card-content">
              <h3 class="hl-card-title">Le d&eacute;but de l'aventure</h3>
              <p class="hl-card-desc">Premi&egrave;re ligne de code d'iCAN. Un r&eacute;seau social pour les proches, sans algorithme, sans pub.</p>
            </div>
          </div>
        </div>
      </div>
    </div>

    <!-- ============ PATCH NOTES ============ -->
    <div v-if="tab === 'patchnotes'" class="pn-container">
      <div class="pn-list">
        <div v-for="patch in patches" :key="patch.version" class="pn-entry">
          <div class="pn-entry-header">
            <span class="pn-version">v{{ patch.version }}</span>
            <span class="pn-date">{{ patch.date }}</span>
            <span v-if="patch.tag" class="pn-tag" :class="patch.tag">{{ tagLabels[patch.tag] }}</span>
          </div>
          <h3 class="pn-entry-title">{{ patch.title }}</h3>
          <ul class="pn-changes">
            <li v-for="(change, i) in patch.changes" :key="i" class="pn-change" :class="change.type">
              <span class="pn-change-badge">{{ changeBadges[change.type] }}</span>
              <span>{{ change.text }}</span>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref } from 'vue'

const tab = ref('highlights')

// ============ HIGHLIGHTS ============
const highlights = [
  {
    version: '4.14.0',
    date: '26 avril 2026',
    icon: '\u{1F3AC}',
    color: '#f2c84b',
    title: 'Hub 3D — iCINEMA, le cinéma du campus',
    description: 'Un nouveau bâtiment ouvre ses portes au nord-ouest du campus : l’<strong>iCINEMA</strong>, avec marquise dorée illuminée, marches d’entrée et salle complète. À l’intérieur, des rangées de fauteuils rouges face à un <strong>écran géant</strong> qui projette en boucle un GIF animé. La salle est éclairée par la lueur chaude qui s’échappe de l’écran. Approche, entre par la porte, installe-toi : la projection est déjà commencée.',
    tags: ['3D', 'Cinéma', 'GIF', 'Bâtiment'],
  },
  {
    version: '4.13.0',
    date: '26 avril 2026',
    icon: '\u{1F514}',
    color: '#1da1f2',
    title: 'Notification sonore + compteur d’onglet pour les nouveaux posts',
    description: 'Quand un nouveau post tombe sur le feed, un petit <strong>"ting"</strong> discret se fait entendre et le titre de l’onglet du navigateur affiche <strong>(1)</strong>, <strong>(2)</strong>, etc. Vous savez tout de suite qu’il y a du nouveau, même si l’onglet iCAN est en arrière-plan. Le compteur disparaît dès que vous chargez les nouveaux posts.',
    tags: ['Notif', 'Audio', 'Feed', 'QoL'],
  },
  {
    version: '4.12.0',
    date: '26 avril 2026',
    icon: '\u{1F7E2}',
    color: '#17bf63',
    title: 'Présence en direct — voyez qui est où',
    description: 'Un <strong>compteur en temps réel</strong> apparaît à côté de chaque onglet de la navigation : Feed, Hub 3D, iWiki, Carte, etc. Vous savez instantanément combien de personnes consultent la même section que vous. Propulsé par <strong>Supabase Realtime presence</strong> — aucune persistance, le compteur baisse dès qu’un utilisateur quitte la section ou se déconnecte.',
    tags: ['Realtime', 'Presence', 'Navigation', 'Live'],
  },
  {
    version: '4.11.0',
    date: '26 avril 2026',
    icon: '\u{1F5BC}',
    color: '#1da1f2',
    title: 'Recadrage des photos — iCharacter & héros iWiki',
    description: 'Plus besoin d’uploader des photos parfaitement carrées : un <strong>recadreur intégré</strong> s’ouvre maintenant lors de la modification de la photo iCharacter et de la photo d’un héros/vilain de l’iWiki. Glissez, zoomez, validez. Le même composant que pour les avatars, en mode carré (400x400) pour respecter le format d’affichage.',
    tags: ['iCharacter', 'iWiki', 'Crop', 'QoL'],
  },
  {
    version: '4.10.0',
    date: '25 avril 2026',
    icon: '\u{1F4CB}',
    color: '#1da1f2',
    title: 'Brouillons de posts — sauvegardez vos templates (texte + image)',
    description: 'Plus besoin de tout retaper : enregistrez vos posts comme <strong>brouillons</strong> directement depuis le composer, <strong>image incluse</strong>. Donnez-leur un nom (ou pas), rechargez-en un en un clic, renommez ou supprimez. Parfait pour vos templates récurrents (annonces, RP, formats spéciaux). Les brouillons sont stockés en local sur votre appareil, isolés par profil.',
    tags: ['Brouillons', 'Templates', 'Images', 'Composer', 'QoL'],
  },
  {
    version: '4.9.0',
    date: '24 avril 2026',
    icon: '\u{1F5FF}',
    color: '#ffd700',
    title: 'Hub 3D \u2014 Place des L\u00e9gendes + parkour fini & sortie de v\u00e9hicule corrig\u00e9e',
    description: 'Au nord du spawn, une nouvelle <strong>Place des L\u00e9gendes</strong> dresse une statue dor\u00e9e par h\u00e9ros (et rouge sombre par vilain) de l\u2019iWiki, avec halo lumineux pulsant et plaque grav\u00e9e. Approche, appuie sur <strong>E</strong>, et tu file droit sur la fiche du h\u00e9ros. C\u00f4t\u00e9 fixes : le <strong>gauntlet final du iPARKOUR</strong> est enfin atteignable (gap apr\u00e8s le slime r\u00e9duit, plateforme \u00e9largie), et on ne reste <strong>plus coinc\u00e9 dans la voiture/le v\u00e9lo</strong> en sortant en diagonale (l\u2019offset de sortie utilise maintenant la vraie demi-AABB rot\u00e9e + reset propre de la physique).',
    tags: ['3D', 'Wiki', 'Statues', 'Parkour', 'Fix'],
  },
  {
    version: '4.8.0',
    date: '20 avril 2026',
    icon: '\u{1F393}',
    color: '#9b59b6',
    title: 'Hub 3D \u2014 Campus universitaire iCAN',
    description: 'Direction l\u2019<strong>universit\u00e9 iCAN</strong> : la ville proc\u00e9durale laisse place \u00e0 un campus enti\u00e8rement construit \u00e0 la main. Au centre, une <strong>fontaine</strong> avec jet d\u2019eau anim\u00e9 entour\u00e9e de bancs. Au nord, la grande <strong>biblioth\u00e8que</strong> avec colonnade classique, fronton et d\u00f4me. \u00c0 l\u2019est le b\u00e2timent des <strong>sciences</strong> (fa\u00e7ade vitr\u00e9e), \u00e0 l\u2019ouest les <strong>arts</strong>, au sud trois <strong>dortoirs</strong> en briques. Un <strong>stade</strong> avec piste et cages, un <strong>parking</strong> rempli de voitures, des arbres, lampadaires et all\u00e9es qui relient tout \u00e7a. C\u00f4t\u00e9 technique : <strong>three-stdlib</strong> int\u00e9gr\u00e9, mat\u00e9riaux PBR, <strong>ombres dynamiques</strong>, ciel atmosph\u00e9rique procédural et tone mapping ACES.',
    tags: ['3D', 'Campus', 'PBR', 'Ombres', 'Sky'],
  },
  {
    version: '4.7.4',
    date: '20 avril 2026',
    icon: '\u{1F6B6}',
    color: '#2ecc71',
    title: 'Hub 3D \u2014 Pi\u00e9tons dans la ville',
    description: 'La ville n\u2019est plus d\u00e9serte ! Une trentaine de <strong>pi\u00e9tons PNJ</strong> d\u00e9ambulent en permanence dans les rues, chacun avec sa propre couleur de v\u00eatement, teinte de peau, vitesse et d\u00e9marche. Ils choisissent des destinations al\u00e9atoires, font des pauses, \u00e9vitent les b\u00e2timents. De quoi donner \u00e2me au Hub m\u00eame quand aucun autre joueur n\u2019est connect\u00e9.',
    tags: ['3D', 'PNJ', 'Ambiance', 'IA'],
  },
  {
    version: '4.7.3',
    date: '20 avril 2026',
    icon: '\u{1F697}',
    color: '#f39c12',
    title: 'Hub 3D \u2014 Voitures conduisibles & capes de h\u00e9ros',
    description: 'Le Hub 3D devient un vrai terrain de jeu : approche n\u2019importe quelle voiture stationn\u00e9e, appuie sur <strong>E</strong> et prends le volant. Physique simple mais satisfaisante (acc\u00e9l\u00e9ration, marche arri\u00e8re, freinage, direction r\u00e9duite \u00e0 haute vitesse), collisions avec les b\u00e2timents et cam\u00e9ra orbitale d\u00e9di\u00e9e. C\u00f4t\u00e9 style : chaque avatar porte d\u00e9sormais une <strong>cape color\u00e9e</strong> qui flotte au vent pendant la marche. Parce qu\u2019iCAN est un univers de super-h\u00e9ros.',
    tags: ['3D', 'V\u00e9hicules', 'Capes', 'Physique'],
  },
  {
    version: '4.7.2',
    date: '20 avril 2026',
    icon: '\u{1F3D9}',
    color: '#3498db',
    title: 'Hub 3D \u2014 Ville proc\u00e9durale & collisions',
    description: 'Le Hub 3D prend vie avec un <strong>environnement urbain g\u00e9n\u00e9r\u00e9 proc\u00e9duralement</strong> : un quadrillage de routes asphalt\u00e9es (avec bandes jaunes), des trottoirs, et des dizaines de b\u00e2timents vari\u00e9s. Immeubles d\u2019habitation avec fen\u00eatres allum\u00e9es, maisons individuelles \u00e0 toit en pente, commerces color\u00e9s avec auvents et enseignes. Des arbres bordent les rues, des lampadaires illuminent les intersections, des voitures sont stationn\u00e9es \u00e7a et l\u00e0. Le tout avec <strong>d\u00e9tection de collisions</strong> : impossible de traverser les murs.',
    tags: ['3D', 'Ville', 'Proc\u00e9dural', 'Collisions'],
  },
  {
    version: '4.7.1',
    date: '20 avril 2026',
    icon: '\u{1F399}',
    color: '#e74c3c',
    title: 'Hub 3D \u2014 Avatars humano\u00efdes & chat vocal de proximit\u00e9',
    description: 'Les cubes c\u00e8dent la place \u00e0 de v\u00e9ritables <strong>avatars humano\u00efdes</strong> (t\u00eate avec photo de profil, torse, bras et jambes articul\u00e9s) avec une animation de marche synchronis\u00e9e. Nouveau : un <strong>chat vocal 3D de proximit\u00e9</strong> en WebRTC pair-\u00e0-pair. Les voix s\u2019att\u00e9nuent avec la distance et viennent du bon c\u00f4t\u00e9 gr\u00e2ce \u00e0 la spatialisation HRTF du navigateur. Un bouton en haut \u00e0 droite active/coupe le micro.',
    tags: ['3D', 'WebRTC', 'Voice', 'Humanoid', 'Multijoueur'],
  },
  {
    version: '4.7.0',
    date: '20 avril 2026',
    icon: '\u{1F30D}',
    color: '#9b59b6',
    title: 'Hub Social 3D \u2014 Un monde partag\u00e9 en temps r\u00e9el',
    description: 'iCAN prend une nouvelle dimension : un <strong>hub 3D multijoueur low-poly</strong> accessible via <code>/game</code>. Chaque utilisateur est incarn\u00e9 par un avatar color\u00e9 qui porte son pseudo et sa photo de profil. <strong>ZQSD</strong> pour se d\u00e9placer, la souris pour regarder autour, <strong>Entr\u00e9e</strong> pour tchatter avec les joueurs pr\u00e9sents. Les positions et messages sont synchronis\u00e9s en temps r\u00e9el via Supabase Realtime (broadcast \u00e9ph\u00e9m\u00e8re \u2014 aucune persistance). Six b\u00e2timents placeholder inspir\u00e9s d\u2019Allentown posent le d\u00e9cor pour les futurs ajouts.',
    tags: ['3D', 'Multijoueur', 'Realtime', 'Three.js', 'Nouveau'],
  },
  {
    version: '4.6.0',
    date: '18 avril 2026',
    icon: '\u{1F4AA}',
    color: '#17bf63',
    title: 'iArena \u2014 Rondes suisses, top-cut & soutiens',
    description: 'iArena passe au format <strong>rondes suisses</strong> : chaque joueur combat plusieurs adversaires (pairings par classement \u00e0 chaque ronde), fini l\u2019\u00e9limination directe. Les nombres impairs de joueurs sont g\u00e9r\u00e9s par des byes rotatifs. \u00c0 l\u2019issue des rondes, les <strong>4 meilleurs s\u2019affrontent en demi-finales + finale</strong> (top-cut) pour d\u00e9signer le vainqueur. Les non-participants peuvent soutenir un combattant en un clic sous le combat en cours : +2 au max des jets (attaque et d\u00e9fense) par soutien, +5 pts si le soutenu remporte le tournoi.',
    tags: ['Arena', 'Swiss', 'Top-cut', 'Soutiens', 'Tournois'],
  },
  {
    version: '4.5.0',
    date: '14 avril 2026',
    icon: '\u2694\uFE0F',
    color: '#ff6b35',
    title: 'iArena \u2014 Refonte en tournois automatiques',
    description: 'iArena devient un tournoi en \u00e9limination directe qui d\u00e9marre automatiquement toutes les 5 heures. L\u2019admin s\u00e9lectionne le pool de combattants, les combats s\u2019encha\u00eenent avec des PV d\u00e9riv\u00e9s de la vigueur et un syst\u00e8me tour par tour bas\u00e9 sur les stats. Toute la communaut\u00e9 peut parier gratuitement sur le vainqueur de chaque combat.',
    tags: ['Arena', 'Tournois', 'PvP', 'Paris', 'Automatique'],
  },
  {
    version: '4.4.0',
    date: '14 avril 2026',
    icon: '\u{1F3F0}',
    color: '#f5a623',
    title: 'Territoires \u2014 Jeu de strat\u00e9gie quotidien',
    description: 'Chaque jour, 7 joueurs choisissent secr\u00e8tement une case. Les cases rapportent plus ou moins de points selon le nombre de joueurs dessus. Bluff, anticipation et th\u00e9orie des jeux au rendez-vous !',
    tags: ['Strat\u00e9gie', 'Quotidien', 'Bluff', 'Leaderboard'],
  },
  {
    version: '4.3.0',
    date: '13 avril 2026',
    icon: '\u2694\uFE0F',
    color: '#e0245e',
    title: 'iArena \u2014 Combat PvP',
    description: 'D\u00e9fiez d\u2019autres joueurs en combat PvP ! Les stats iCharacter d\u00e9terminent l\u2019issue en 3 rounds avec une part d\u2019al\u00e9atoire. Misez vos iCoins, grimpez le classement ELO et maintenez votre win streak.',
    tags: ['PvP', 'Arena', 'ELO', 'iCoins', 'Combat'],
  },
  {
    version: '4.2.0',
    date: '13 avril 2026',
    icon: '\u{1F3AE}',
    color: '#9b59b6',
    title: 'iGames \u2014 Mini-jeu iRunner',
    description: 'Uploadez votre photo et incarnez-la dans un mini-jeu inspir\u00e9 du dinosaure Chrome ! Sautez par-dessus les bombes et les vilains, battez votre record et d\u00e9fiez vos amis.',
    tags: ['Jeu', 'Canvas', 'Fun', 'iRunner'],
  },
  {
    version: '4.1.0',
    date: '13 avril 2026',
    icon: '\u{1F4D6}',
    color: '#1da1f2',
    title: 'iWiki \u2014 Encyclop\u00e9die compl\u00e8te',
    description: 'L\u2019iWiki s\u2019enrichit d\u2019une encyclop\u00e9die compl\u00e8te ! Cr\u00e9ez des articles pour les lieux, PNJ, objets, \u00e9v\u00e9nements et factions. Reliez-les entre eux avec des liens hypertexte [[Nom de l\u2019article]]. Chaque article dispose d\u2019une page d\u00e9di\u00e9e avec image, tags et contenu riche.',
    tags: ['Wiki', 'Encyclop\u00e9die', 'Articles', 'Hyperlinks'],
  },
  {
    version: '4.0.0',
    date: '12 avril 2026',
    icon: '\u{1F4D6}',
    color: '#ffd700',
    title: 'iWiki \u2014 Encyclop\u00e9die des H\u00e9ros & Vilains',
    description: 'D\u00e9couvrez l\u2019iWiki ! Une vitrine stylis\u00e9e pr\u00e9sente les H\u00e9ros et Vilains de la Nation avec des animations comic/Marvel, des particules et des effets 3D. Un r\u00e9pertoire complet permet de rechercher et parcourir tous les personnages. Les admins peuvent cr\u00e9er et g\u00e9rer les fiches (pouvoirs, stats, histoire, alli\u00e9s/ennemis).',
    tags: ['Wiki', 'H\u00e9ros', 'Vilains', 'Animations', 'Admin'],
  },
  {
    version: '3.4.0',
    date: '12 avril 2026',
    icon: '\u{26A1}',
    color: '#e0245e',
    title: 'Temps r\u00e9el — Supabase Realtime',
    description: 'L\u2019app est d\u00e9sormais r\u00e9active en temps r\u00e9el ! Les messages arrivent instantan\u00e9ment, le feed affiche un bandeau \u00ab Nouveaux posts \u00bb quand d\u2019autres publient, et les commentaires apparaissent en direct sur les posts.',
    tags: ['Realtime', 'Messages', 'Feed', 'Commentaires', 'WebSocket'],
  },
  {
    version: '3.3.0',
    date: '11 avril 2026',
    icon: '\u{1F5FA}',
    color: '#17bf63',
    title: 'Clustering carte & navigation filtres',
    description: 'Les lieux proches sur la carte se regroupent automatiquement en bulles. Survolez un cluster pour d\u00e9ployer les marqueurs en \u00e9ventail. Chaque filtre de cat\u00e9gorie affiche d\u00e9sormais la liste des lieux au survol, avec navigation directe en un clic.',
    tags: ['Carte', 'Clustering', 'Filtres', 'Navigation', 'UX'],
  },
  {
    version: '3.2.1',
    date: '9 avril 2026',
    icon: '\u{2709}',
    color: '#1da1f2',
    title: 'Fix Chart iCHARACTER',
    description: 'Correction de l\'affichage de la stat d\'intelligence du radar chart dans les fiches personnage iCHARACTER.',
    tags: ['Fix', 'Chart', 'iCHARACTER', 'Radar', 'Stats'],
  },
  {
    version: '3.2.0',
    date: '7 avril 2026',
    icon: '\u{2709}',
    color: '#1da1f2',
    title: 'Messages redesign\u00e9s style X',
    description: 'La page Messages adopte un layout 2 colonnes inspir\u00e9 de X/Twitter ! Liste des conversations \u00e0 gauche avec apercu du dernier message, indicateur non-lu et timestamp. Conversation active \u00e0 droite. Les notifications et badges se mettent \u00e0 jour instantan\u00e9ment.',
    tags: ['Messages', 'UI', 'Twitter-style', 'Split-view'],
  },
  {
    version: '3.1.0',
    date: '5 avril 2026',
    icon: '\u{1F4CD}',
    color: '#f39c12',
    title: 'Mentions de lieux sur la carte',
    description: 'Liez vos posts aux lieux de la carte d\'Allentown ! Tapez < dans un post pour mentionner un lieu avec autocompl\u00e9tion. Les mentions s\'affichent en dor\u00e9 et redirigent vers la carte. Chaque lieu affiche d\u00e9sormais les 5 derniers posts qui le mentionnent.',
    tags: ['Carte', 'Mentions', 'Lieux', 'Immersion', 'JDR'],
  },
  {
    version: '3.0.0',
    date: '5 avril 2026',
    icon: '\u{1F9D9}',
    color: '#9b59b6',
    title: 'iCHARACTER \u2014 Fiches Personnage',
    description: 'Chaque profil poss\u00e8de d\u00e9sormais sa fiche personnage compl\u00e8te ! Photo, identit\u00e9 (nom, pr\u00e9nom, nationalit\u00e9, sexe, lieu et date de naissance) et 5 comp\u00e9tences (Charisme, Intelligence, Force, Vigueur, Mobilit\u00e9) visualis\u00e9es sur un radar chart pentagone SVG interactif. Inventaire d\'objets avec \u00e9mojis. Modifiez votre fiche, consultez celles des autres.',
    tags: ['Fiche perso', 'Stats', 'Inventaire', 'Radar chart', 'JDR'],
  },
  {
    version: '3.0.0',
    date: '5 avril 2026',
    icon: '\u{1F3E6}',
    color: '#2ecc71',
    title: 'iBANK \u2014 Syst\u00e8me bancaire',
    description: 'Un syst\u00e8me bancaire complet pour l\u2019univers du JDR ! Chaque profil a un compte en dollars avec solde, transferts entre joueurs, historique des transactions et une section admin pour cr\u00e9diter ou d\u00e9biter librement les comptes.',
    tags: ['Banque', 'Transferts', 'Dollars', 'Admin', '\u00c9conomie'],
  },
  {
    version: '2.16.0',
    date: '4 avril 2026',
    icon: '\u{1F5FA}',
    color: '#1da1f2',
    title: 'Carte interactive d\'Allentown',
    description: 'Explorez la ville d\'Allentown directement depuis l\'app ! Carte sombre interactive avec les lieux cl\u00e9s de l\'univers : maisons des h\u00e9ros, lyc\u00e9e, QG, repaires de vilains... Les admins peuvent ajouter et g\u00e9rer les emplacements, chaque lieu peut \u00eatre li\u00e9 \u00e0 un personnage.',
    tags: ['Carte', 'Immersion', 'Leaflet', 'Lieux', 'Admin'],
  },
  {
    version: '2.15.0',
    date: '4 avril 2026',
    icon: '\u2B50',
    color: '#FFD700',
    title: 'R\u00f4le Hero',
    description: 'Nouveau r\u00f4le Hero attribu\u00e9 par les admins ! Les Heroes ont des posts ultra-distincts avec bordure anim\u00e9e d\u00e9grad\u00e9e, effet glow et badge \u00e9toile. Chaque Hero peut personnaliser ses couleurs depuis les param\u00e8tres.',
    tags: ['Hero', 'R\u00f4le', 'Personnalisation', 'Admin', 'Animation'],
  },
  {
    version: '2.10.0',
    date: '1 avril 2026',
    icon: '✏️',
    color: '#9b59b6',
    title: 'Citations (Quote Tweets)',
    description: 'Citez n\'importe quel post ou commentaire avec votre propre texte, comme sur Twitter. Le contenu original s\'affiche en embed dans votre publication.',
    tags: ['Citations', 'Reposts', 'Commentaires', 'Embed'],
  },
  {
    version: '2.7.1',
    date: '30 mars 2026',
    title: 'Pictogrammes & animations des commentaires',
    tag: 'patch',
    changes: [
      { type: 'improved', text: 'Nouveaux pictogrammes SVG pour les boutons Répondre et Like dans les commentaires, avec animation de clic.' },
      { type: 'fixed', text: 'Alignement et rendu parfaits des icônes dans CommentCard.' },
    ],
  },
  {
    version: '2.7.0',
    date: '30 mars 2026',
    icon: '#\uFE0F\u20E3',
    color: '#3498db',
    title: 'Tendances par hashtags',
    description: 'Les tendances fonctionnent d\u00e9sormais avec des #hashtags. Le panneau lat\u00e9ral est scrollable et le widget DM repositionn\u00e9 pour ne plus g\u00eaner les utilisateurs actifs.',
    tags: ['Hashtags', 'Tendances', 'UI', 'Scroll'],
  },
  {
    version: '2.6.0',
    date: '30 mars 2026',
    icon: '\u{1F514}',
    color: '#e74c3c',
    title: 'Notifications redesign\u00e9es',
    description: 'Syst\u00e8me de notifications enti\u00e8rement repens\u00e9 : onglets par profil avec badge individuel, filtres par type (likes, commentaires, reposts), indicateur de profil destinataire, et design am\u00e9lior\u00e9.',
    tags: ['Multi-profils', 'Filtres', 'Notifications', 'Redesign'],
  },
  {
    version: '2.5.0',
    date: '28 mars 2026',
    icon: '\u{1F6E1}',
    color: '#e74c3c',
    title: 'Audit de s\u00e9curit\u00e9',
    description: 'Corrections majeures : suppression des cl\u00e9s expos\u00e9es, protection XSS, validation des entr\u00e9es, politique CSP, et s\u00e9curisation des requ\u00eates.',
    tags: ['S\u00e9curit\u00e9', 'XSS', 'CSP', 'Validation'],
  },
  {
    version: '2.4.0',
    date: '28 mars 2026',
    icon: '\u{2705}',
    color: '#1da1f2',
    title: 'Certification Admin',
    description: 'Les comptes administrateurs sont d\u00e9sormais identifi\u00e9s par un badge certifi\u00e9 bleu \u00e0 c\u00f4t\u00e9 de leur nom. Leurs posts sont subtilement mis en avant avec une bordure et un fond color\u00e9.',
    tags: ['Badge certifi\u00e9', 'Posts admin', 'Highlight'],
  },
  {
    version: '2.3.0',
    date: '28 mars 2026',
    icon: '\u{1F4DD}',
    color: '#2ecc71',
    title: 'Bio & Visionneuse avatar',
    description: 'Ajoutez une bio \u00e0 votre profil pour vous pr\u00e9senter en quelques mots. Cliquez sur la photo de profil pour l\'afficher en grand dans une lightbox \u00e9l\u00e9gante.',
    tags: ['Bio', 'Lightbox avatar', 'Profil'],
  },
  {
    version: '2.2.0',
    date: '28 mars 2026',
    icon: '\u{1F50D}',
    color: '#3498db',
    title: 'Recherche & Tendances',
    description: 'Nouvelle page de recherche pour trouver des profils et des posts. Panneau lat\u00e9ral droit avec les mots-cl\u00e9s tendances et les utilisateurs les plus actifs de la semaine.',
    tags: ['Recherche', 'Tendances', 'Utilisateurs actifs', 'Panneau lat\u00e9ral'],
  },
  {
    version: '2.1.0',
    date: '28 mars 2026',
    icon: '\u{2702}',
    color: '#9b59b6',
    title: 'Sidebar & Recadrage avatar',
    description: 'Nouvelle navigation lat\u00e9rale inspir\u00e9e de Twitter avec acc\u00e8s rapide au Feed, Messages, Profil, Param\u00e8tres et Admin. Recadrage interactif de la photo de profil avec zoom et d\u00e9placement.',
    tags: ['Sidebar', 'Crop avatar', 'Navigation', 'Mobile'],
  },
  {
    version: '2.0.0',
    date: '28 mars 2026',
    icon: '\u{1F6E1}',
    color: '#e74c3c',
    title: 'Panel Administrateur',
    description: 'Un tableau de bord complet pour les admins : statistiques en temps r\u00e9el, gestion des utilisateurs, bans temporaires, mod\u00e9ration des commentaires, et surveillance de toutes les conversations priv\u00e9es.',
    tags: ['Admin', 'Mod\u00e9ration', 'Bans temporaires', 'Surveillance DM'],
  },
  {
    version: '1.9.0',
    date: '28 mars 2026',
    icon: '\u{1F3A8}',
    color: '#1da1f2',
    title: 'Profil inspir\u00e9 de Twitter',
    description: 'Page de profil enti\u00e8rement redesign\u00e9e : banni\u00e8re gradient, avatar en overlay, statistiques, 4 onglets (Posts, Reposts, J\'aime, M\u00e9dias) et grille m\u00e9dia d\u00e9di\u00e9e.',
    tags: ['Redesign profil', 'Grille m\u00e9dias', 'Onglets', 'Twitter-style'],
  },
  {
    version: '1.8.0',
    date: '28 mars 2026',
    icon: '\u{1F514}',
    color: '#e74c3c',
    title: 'Notifications & Discord',
    description: 'Soyez alert\u00e9 en temps r\u00e9el : cloche de notifications in-app pour les likes, commentaires, r\u00e9ponses et reposts. Chaque nouveau post est aussi envoy\u00e9 automatiquement sur Discord via webhook.',
    tags: ['Notifications in-app', 'Webhook Discord', 'Temps r\u00e9el'],
  },
  {
    version: '1.6.0',
    date: '28 mars 2026',
    icon: '\u{1F465}',
    color: '#9b59b6',
    title: 'Groupes de discussion',
    description: 'Cr\u00e9ez des conversations de groupe avec vos amis. Nommez le groupe, ajoutez des membres et discutez \u00e0 plusieurs en temps r\u00e9el directement depuis le widget DM.',
    tags: ['Groupe DM', 'Multi-membres', 'Recherche de membres'],
  },
  {
    version: '1.5.0',
    date: '28 mars 2026',
    icon: '\u{1F5BC}',
    color: '#e67e22',
    title: 'Images en DM & Patch Notes',
    description: 'Envoyez des photos dans vos conversations priv\u00e9es. Pr\u00e9visualisation avant envoi, support JPG/PNG/GIF/WebP. Plus une toute nouvelle page de suivi des mises \u00e0 jour.',
    tags: ['Photos DM', 'Pr\u00e9visualisation', 'Patch Notes'],
  },
  {
    version: '1.4.0',
    date: '28 mars 2026',
    icon: '\u{1F6E1}',
    color: '#794bc4',
    title: 'S\u00e9curit\u00e9 & Qualit\u00e9 de vie',
    description: 'Rate limiting anti-spam sur toutes les actions, validation des uploads, liste des likers sur chaque post, et bouton refresh d\u00e9plac\u00e9 en haut du feed.',
    tags: ['Anti-spam', 'Rate limit', 'Liste des likes'],
  },
  {
    version: '1.3.0',
    date: '28 mars 2026',
    icon: '\u{2709}',
    color: '#1da1f2',
    title: 'Widget DM & Images dans les posts',
    description: 'Un widget de messagerie flottant en bas \u00e0 gauche, inspir\u00e9 de X/Twitter. Plus besoin de quitter la page pour discuter. Publiez aussi des images avec vos posts.',
    tags: ['Widget flottant', 'Photos posts', 'Badge non-lus'],
  },
  {
    version: '1.2.0',
    date: '28 mars 2026',
    icon: '\u{1F4AC}',
    color: '#e0245e',
    title: 'Refonte commentaires & reposts',
    description: 'Commentaires enti\u00e8rement repens\u00e9s : likes, r\u00e9ponses imbriqu\u00e9es avec fil visuel, avatars. Les reposts affichent maintenant le contenu original avec toggle.',
    tags: ['R\u00e9ponses imbriqu\u00e9es', 'Likes commentaires', 'Reposts am\u00e9lior\u00e9s'],
  },
  {
    version: '1.1.0',
    date: '27 mars 2026',
    icon: '\u{1F464}',
    color: '#17bf63',
    title: 'Multi-profils & Param\u00e8tres',
    description: 'Un seul compte, plusieurs identit\u00e9s. Cr\u00e9ez des alias, changez de profil en un clic, personnalisez avatar et pseudo pour chacun.',
    tags: ['Multi-profils', 'Switcher', 'Avatars', 'Param\u00e8tres'],
  },
  {
    version: '1.0.0',
    date: '27 mars 2026',
    icon: '\u{2B50}',
    color: '#ffad1f',
    title: 'Lancement d\'iCAN',
    description: 'Le r\u00e9seau social pour 10\u201350 amis. Feed de posts, likes, reposts, commentaires, messages directs, authentification, th\u00e8me sombre et d\u00e9ploiement GitHub Pages.',
    tags: ['Feed', 'Likes', 'DM', 'Auth', 'D\u00e9ploiement'],
  },
]

// ============ PATCH NOTES ============
const tagLabels = {
  major: 'MAJEUR',
  minor: 'MINEUR',
  hotfix: 'HOTFIX',
}

const changeBadges = {
  new: 'NOUVEAU',
  improved: 'AM\u00c9LIOR\u00c9',
  fixed: 'CORRIG\u00c9',
  changed: 'MODIFI\u00c9',
  removed: 'RETIR\u00c9',
  security: 'S\u00c9CURIT\u00c9',
}

const patches = [
  {
    version: '4.14.0',
    date: '26 avril 2026',
    title: 'iCINEMA dans le Hub 3D',
    tag: 'minor',
    changes: [
      { type: 'new', text: 'Nouveau module `src/lib/game3d/cinema.js` — bâtiment cinéma complet (murs, plafond, marches, marquise iCINEMA)' },
      { type: 'new', text: 'Écran géant projetant un GIF animé via canvas-texture (<img> HTML recopié frame par frame, ~16 fps)' },
      { type: 'new', text: 'Intérieur meublé : 32 sièges rouges en 4 rangées avec allée centrale, point light chaud devant l’écran' },
      { type: 'improved', text: 'Cinéma intégré au moteur (engine.js) : obstacles murs en U avec porte, animation et dispose propres' },
    ],
  },
  {
    version: '4.13.0',
    date: '26 avril 2026',
    title: 'Ting sonore + (n) dans le titre de l’onglet',
    tag: 'minor',
    changes: [
      { type: 'new', text: 'Son "ting" généré via Web Audio API à chaque nouveau post realtime sur le feed' },
      { type: 'new', text: 'Le titre de l’onglet du navigateur affiche (n) avec le nombre de posts en attente' },
      { type: 'improved', text: 'Reset automatique du titre au clic sur le bandeau "X nouveaux posts" ou en quittant le feed' },
    ],
  },
  {
    version: '4.12.0',
    date: '26 avril 2026',
    title: 'Compteurs de présence en direct',
    tag: 'minor',
    changes: [
      { type: 'new', text: 'Nouveau store `presence` basé sur Supabase Realtime presence (canal `global-presence`)' },
      { type: 'new', text: 'Badge de présence (point vert + nombre) à côté de chaque onglet de la sidebar' },
      { type: 'new', text: 'Compteurs également affichés dans la nav mobile (top-bar et menu Plus)' },
      { type: 'improved', text: 'Mise à jour automatique au changement de route et au switch de profil' },
    ],
  },
  {
    version: '4.11.0',
    date: '26 avril 2026',
    title: 'Recadrage photos iCharacter & iWiki',
    tag: 'minor',
    changes: [
      { type: 'new', text: 'Recadreur d’image (drag + zoom) lors de l’upload de la photo iCharacter' },
      { type: 'new', text: 'Recadreur d’image lors de la modification de la photo d’un héros/vilain iWiki' },
      { type: 'improved', text: 'ImageCropper : nouveau prop `shape` (circle | square) et titre personnalisable' },
      { type: 'improved', text: 'Limite 5 Mo appliquée également sur ces uploads' },
    ],
  },
  {
    version: '4.10.0',
    date: '25 avril 2026',
    title: 'Brouillons de posts',
    tag: 'minor',
    changes: [
      { type: 'new', text: 'Bouton brouillons (icône presse-papier) dans le PostComposer avec compteur' },
      { type: 'new', text: 'Modal de gestion : liste, chargement, renommage et suppression des brouillons' },
      { type: 'new', text: 'Sauvegarde de l’image attachée dans le brouillon (encodée en base64)' },
      { type: 'new', text: 'Badge image sur les brouillons qui en contiennent une' },
      { type: 'new', text: 'Champ nom optionnel — pratique pour créer des templates récurrents' },
      { type: 'new', text: 'Stockage localStorage isolé par profil (clé ican_post_drafts_v1)' },
    ],
  },
  {
    version: '4.8.0',
    date: '20 avril 2026',
    title: 'Hub 3D \u2014 Campus iCAN & moteur avanc\u00e9',
    tag: 'major',
    changes: [
      { type: 'new', text: 'Carte enti\u00e8rement repens\u00e9e : campus universitaire iCAN (remplace la ville proc\u00e9durale)' },
      { type: 'new', text: 'Biblioth\u00e8que avec colonnade, fronton triangulaire, d\u00f4me et escalier' },
      { type: 'new', text: 'B\u00e2timents modernes (sciences, arts, salles de cours) avec fa\u00e7ades vitr\u00e9es' },
      { type: 'new', text: 'Trois dortoirs en briques avec toits en pente et fen\u00eatres \u00e9missives' },
      { type: 'new', text: 'Fontaine centrale avec jet anim\u00e9, vasque, colonne et bancs tout autour' },
      { type: 'new', text: 'Stade avec piste rouge, pelouse ronde et cages de but' },
      { type: 'new', text: 'Parking avec voitures stationn\u00e9es + voitures drivables dans les all\u00e9es' },
      { type: 'new', text: 'All\u00e9es en X depuis la fontaine, lampadaires et arbres sur tout le campus' },
      { type: 'new', text: 'Int\u00e9gration de three-stdlib (RoundedBoxGeometry, Sky procédural)' },
      { type: 'new', text: 'Ciel atmosph\u00e9rique procédural (Rayleigh/Mie) avec soleil coh\u00e9rent' },
      { type: 'new', text: 'Ombres dynamiques (PCF Soft) avec frustum de shadow qui suit le joueur' },
      { type: 'new', text: 'Mat\u00e9riaux PBR (MeshStandardMaterial) avec roughness/metalness' },
      { type: 'new', text: 'Tone mapping ACES Filmic pour des couleurs plus naturelles' },
      { type: 'changed', text: 'Avatars, pi\u00e9tons et voitures projettent maintenant des ombres' },
    ],
  },
  {
    version: '4.7.4',
    date: '20 avril 2026',
    title: 'Hub 3D \u2014 Pi\u00e9tons',
    tag: 'minor',
    changes: [
      { type: 'new', text: '28 pi\u00e9tons PNJ d\u00e9ambulent dans la ville (seed fixe pour coh\u00e9rence)' },
      { type: 'new', text: 'Palettes de couleurs vari\u00e9es : 10 teintes de v\u00eatements, 5 pantalons, 5 carnations' },
      { type: 'new', text: 'Comportement wander : cible al\u00e9atoire, marche vers elle, pause occasionnelle \u00e0 l\u2019arriv\u00e9e' },
      { type: 'new', text: '\u00c9vitement basique des b\u00e2timents (re-ciblage si chemin bloqu\u00e9)' },
      { type: 'new', text: 'Animation de marche (balancement bras / jambes) avec phase individuelle par pi\u00e9ton' },
      { type: 'new', text: 'Rotation fluide vers la direction de d\u00e9placement' },
    ],
  },
  {
    version: '4.7.3',
    date: '20 avril 2026',
    title: 'Hub 3D \u2014 Voitures conduisibles & capes',
    tag: 'major',
    changes: [
      { type: 'new', text: 'Voitures conduisibles : approche une voiture, appuie sur E pour embarquer, E de nouveau pour sortir' },
      { type: 'new', text: 'Physique v\u00e9hicule : acc\u00e9l\u00e9ration progressive, marche arri\u00e8re, freinage, drag naturel' },
      { type: 'new', text: 'Direction d\u00e9pendante de la vitesse (rayon de braquage plus large en pleine vitesse)' },
      { type: 'new', text: 'Cam\u00e9ra orbitale d\u00e9di\u00e9e en conduite (recul\u00e9e et sur\u00e9lev\u00e9e)' },
      { type: 'new', text: 'Collision v\u00e9hicule/b\u00e2timents avec rebond att\u00e9nu\u00e9' },
      { type: 'new', text: 'Hint d\u2019interaction \u00e0 l\u2019\u00e9cran : touche E affich\u00e9e quand une voiture est \u00e0 port\u00e9e' },
      { type: 'new', text: 'Capes pour tous les avatars : couleur d\u00e9riv\u00e9e du profile_id, animation de flottement pendant la marche' },
      { type: 'improved', text: 'Obstacle de la voiture retir\u00e9 puis r\u00e9ins\u00e9r\u00e9 dynamiquement \u00e0 l\u2019entr\u00e9e/sortie' },
    ],
  },
  {
    version: '4.7.2',
    date: '20 avril 2026',
    title: 'Hub 3D \u2014 Ville proc\u00e9durale',
    tag: 'major',
    changes: [
      { type: 'new', text: 'Environnement urbain proc\u00e9dural : quadrillage 7x7 de rues avec routes, trottoirs et intersections' },
      { type: 'new', text: 'B\u00e2timents vari\u00e9s g\u00e9n\u00e9r\u00e9s al\u00e9atoirement (seed fixe pour coh\u00e9rence) : immeubles, maisons, commerces' },
      { type: 'new', text: 'Immeubles d\u2019habitation : fa\u00e7ades textur\u00e9es avec fen\u00eatres allum\u00e9es (35% de chance par fen\u00eatre)' },
      { type: 'new', text: 'Maisons avec toits en pente (prisme triangulaire extrud\u00e9), portes et fen\u00eatres' },
      { type: 'new', text: 'Commerces color\u00e9s avec vitrines, auvents inclin\u00e9s et enseignes' },
      { type: 'new', text: 'Arbres (tronc + feuillage icosaedrique) dispos\u00e9s le long des trottoirs' },
      { type: 'new', text: 'Lampadaires avec bulbes \u00e9missifs aux intersections' },
      { type: 'new', text: 'Voitures stationn\u00e9es (carrosserie + cabine + 4 roues) avec couleurs vari\u00e9es' },
      { type: 'new', text: 'D\u00e9tection de collisions AABB : impossible de traverser b\u00e2timents, arbres, voitures' },
      { type: 'new', text: 'Glissement le long des murs : le mouvement est conserv\u00e9 sur l\u2019axe non-bloqu\u00e9' },
      { type: 'new', text: 'Lumi\u00e8re h\u00e9misph\u00e9rique ajout\u00e9e pour un ciel plus r\u00e9aliste, brouillard \u00e9loign\u00e9 (60\u2013180m)' },
      { type: 'new', text: 'Monde agrandi \u00e0 ~180m de c\u00f4t\u00e9 pour accueillir la ville' },
    ],
  },
  {
    version: '4.7.1',
    date: '20 avril 2026',
    title: 'Hub 3D \u2014 Humano\u00efdes & vocal',
    tag: 'major',
    changes: [
      { type: 'new', text: 'Avatars humano\u00efdes low-poly : t\u00eate (avec photo de profil plaqu\u00e9e), torse, bras et jambes articul\u00e9s' },
      { type: 'new', text: 'Animation de marche : balancement bras/jambes quand le perso bouge (local et distant)' },
      { type: 'new', text: 'Vue 3\u00e8me personne : cam\u00e9ra orbitale derri\u00e8re l\u2019avatar, contr\u00f4l\u00e9e \u00e0 la souris' },
      { type: 'new', text: 'Chat vocal de proximit\u00e9 en WebRTC P2P (signaling via Supabase broadcast)' },
      { type: 'new', text: 'Audio spatialis\u00e9 (THREE.PositionalAudio) : distance de r\u00e9f\u00e9rence 3m, port\u00e9e max 25m, rolloff lin\u00e9aire' },
      { type: 'new', text: 'Bouton micro en haut \u00e0 droite : activer / mute / unmute avec feedback visuel' },
      { type: 'new', text: 'Couleur de v\u00eatement d\u00e9riv\u00e9e du profile_id (unique par joueur)' },
      { type: 'fix', text: 'PointerLockControls retir\u00e9 au profit d\u2019une gestion manuelle (fix de compatibilit\u00e9 avec Three.js r184)' },
    ],
  },
  {
    version: '4.7.0',
    date: '20 avril 2026',
    title: 'Hub Social 3D',
    tag: 'major',
    changes: [
      { type: 'new', text: 'Nouvelle route /game : monde 3D multijoueur low-poly en temps r\u00e9el (Three.js + Supabase broadcast)' },
      { type: 'new', text: 'Avatar personnel avec pseudo affich\u00e9 et photo de profil plaqu\u00e9e sur la t\u00eate' },
      { type: 'new', text: 'Contr\u00f4les ZQSD + souris (PointerLock), collisions simples sur les bords du monde' },
      { type: 'new', text: 'Pr\u00e9sence live des autres joueurs : join/leave via presence channel Supabase' },
      { type: 'new', text: 'Positions synchronis\u00e9es \u00e0 10 Hz, interpolation c\u00f4t\u00e9 client pour un rendu fluide' },
      { type: 'new', text: 'Chat de proximit\u00e9 int\u00e9gr\u00e9 (Entr\u00e9e pour \u00e9crire, \u00c9chap pour lib\u00e9rer le curseur)' },
      { type: 'new', text: 'D\u00e9cor initial : 6 b\u00e2timents placeholder inspir\u00e9s d\u2019Allentown, sol herbeux, skybox et brouillard' },
      { type: 'new', text: 'Lien \u00ab Hub 3D \u00bb ajout\u00e9 \u00e0 la sidebar desktop et au menu Plus mobile' },
      { type: 'new', text: 'Lazy-loading strict : Three.js n\u2019est t\u00e9l\u00e9charg\u00e9 qu\u2019\u00e0 la visite de /game' },
    ],
  },
  {
    version: '4.6.0',
    date: '18 avril 2026',
    title: 'iArena \u2014 Rondes suisses, top-cut & soutiens',
    tag: 'major',
    changes: [
      { type: 'new', text: 'Format rondes suisses : chaque joueur combat plusieurs adversaires, pairings par classement' },
      { type: 'new', text: 'Nombre de rondes = min(N-1, 5) pour garantir \u00ab tout le monde se bat contre tout le monde \u00bb dans les petits tournois' },
      { type: 'new', text: 'Classement Swiss en direct : V (victoires), D (d\u00e9faites), byes' },
      { type: 'new', text: 'Gestion native des nombres impairs : un joueur diff\u00e9rent re\u00e7oit un bye (+1V) \u00e0 chaque ronde' },
      { type: 'new', text: 'Top-cut : \u00e0 la fin des rondes suisses, les 4 meilleurs s\u2019affrontent en demi-finales (#1 vs #4, #2 vs #3), petite finale (3e place) puis grande finale' },
      { type: 'new', text: 'Vainqueur du tournoi = gagnant de la finale top-cut (ou t\u00eate du classement si <4 joueurs)' },
      { type: 'new', text: 'Bouton \u00ab Soutenir \u00bb compact sous chaque combattant du combat en cours' },
      { type: 'new', text: 'Chaque soutien ajoute +2 au max des jets (attaque ET d\u00e9fense) du combattant soutenu' },
      { type: 'new', text: 'Le soutien est d\u00e9sormais d\u00e9finitif : une fois attribu\u00e9, impossible de le retirer ou de le changer' },
      { type: 'new', text: 'Avatars des supporters affich\u00e9s sous chaque combattant pour voir qui soutient qui' },
      { type: 'new', text: '+5 pts au classement si le combattant soutenu remporte le tournoi' },
      { type: 'new', text: 'Les participants du bracket sont re-d\u00e9riv\u00e9s dynamiquement si les soutiens modifient le classement pr\u00e9dit' },
      { type: 'removed', text: 'Bracket single-elim remplac\u00e9 par Swiss + top-cut des 4 meilleurs' },
      { type: 'fix', text: 'Fini les joueurs ignor\u00e9s : tous les joueurs du pool participent (pool de 5 \u2192 5 joueurs actifs)' },
    ],
  },
  {
    version: '4.5.0',
    date: '14 avril 2026',
    title: 'iArena \u2014 Refonte en tournois automatiques',
    tag: 'major',
    changes: [
      { type: 'new', text: 'Tournois en \u00e9limination directe d\u00e9marr\u00e9s automatiquement toutes les 5 heures' },
      { type: 'new', text: 'Pool de joueurs g\u00e9r\u00e9 par l\u2019admin (2, 4 ou 8 combattants par tournoi)' },
      { type: 'new', text: 'Combats tour par tour : une stat al\u00e9atoire par tour, jet attaquant vs jet d\u00e9fenseur, d\u00e9g\u00e2ts = diff\u00e9rence' },
      { type: 'new', text: 'PV d\u00e9riv\u00e9s de la vigueur (20 + vigueur \u00d7 10)' },
      { type: 'new', text: 'Affichage en grand du combat en cours avec barres de PV anim\u00e9es et log tour par tour' },
      { type: 'new', text: 'Paris gratuits sur chaque combat : +10 pts par pari correct' },
      { type: 'new', text: 'Vainqueur du tournoi : +100 pts au classement' },
      { type: 'new', text: 'Mini-bracket visuel avec les r\u00e9sultats de chaque round' },
      { type: 'removed', text: 'Syst\u00e8me de d\u00e9fis 1v1 \u00e0 la demande remplac\u00e9 par les tournois' },
      { type: 'removed', text: 'Mises en iCoins retir\u00e9es au profit des paris gratuits' },
    ],
  },
  {
    version: '4.4.0',
    date: '14 avril 2026',
    title: 'Territoires \u2014 Jeu de strat\u00e9gie quotidien',
    tag: 'major',
    changes: [
      { type: 'new', text: '4 cases avec r\u00e8gles de scoring diff\u00e9rentes (Jackpot 5pts si seul, Risque 3pts si \u2264 2, Partage 2pts si \u2264 3, Refuge 1pt pour tous)' },
      { type: 'new', text: 'Vote quotidien verrouill\u00e9 apr\u00e8s choix, r\u00e9sultats r\u00e9v\u00e9l\u00e9s quand tous ont vot\u00e9' },
      { type: 'new', text: 'Leaderboard cumul\u00e9 avec points totaux et jours jou\u00e9s' },
      { type: 'new', text: 'Historique des jours pr\u00e9c\u00e9dents' },
      { type: 'new', text: 'Gestion admin des 7 joueurs' },
    ],
  },
  {
    version: '4.3.0',
    date: '13 avril 2026',
    title: 'iArena \u2014 Combat PvP',
    tag: 'major',
    changes: [
      { type: 'new', text: 'Mode iArena : combat PvP asynchrone bas\u00e9 sur les stats iCharacter' },
      { type: 'new', text: '3 rounds (Attaque, D\u00e9fense, Final) avec jets al\u00e9atoires' },
      { type: 'new', text: 'Mise d\u2019iCoins optionnelle sur les combats' },
      { type: 'new', text: 'Classement ELO avec win/loss et streak' },
      { type: 'new', text: 'Replay d\u00e9taill\u00e9 round par round des combats' },
      { type: 'new', text: 'Syst\u00e8me de d\u00e9fis : envoyer, accepter ou d\u00e9cliner' },
    ],
  },
  {
    version: '4.2.0',
    date: '13 avril 2026',
    title: 'iGames \u2014 Mini-jeu iRunner',
    tag: 'minor',
    changes: [
      { type: 'new', text: 'Nouvel onglet iGames dans la navigation' },
      { type: 'new', text: 'Mini-jeu iRunner : uploadez une photo qui devient votre personnage' },
      { type: 'new', text: 'Saut avec Espace / Clic / Tap, obstacles bombes et vilains' },
      { type: 'new', text: 'Score en temps r\u00e9el et meilleur score sauvegard\u00e9 localement' },
      { type: 'new', text: 'Responsive : jouable sur mobile et desktop' },
    ],
  },
  {
    version: '4.1.0',
    date: '13 avril 2026',
    title: 'iWiki \u2014 Encyclop\u00e9die compl\u00e8te',
    tag: 'minor',
    changes: [
      { type: 'new', text: 'Onglet Encyclop\u00e9die dans iWiki avec articles par cat\u00e9gorie (lieu, PNJ, objet, \u00e9v\u00e9nement, faction)' },
      { type: 'new', text: 'Pages d\u00e9taill\u00e9es pour chaque article avec image, tags, et contenu riche' },
      { type: 'new', text: 'Syst\u00e8me de liens [[Nom]] entre articles (style Wikip\u00e9dia)' },
      { type: 'new', text: 'Recherche et filtres par cat\u00e9gorie dans le r\u00e9pertoire des articles' },
      { type: 'new', text: 'Gestion admin : cr\u00e9ation, \u00e9dition, suppression et upload d\u2019images' },
    ],
  },
  {
    version: '4.0.0',
    date: '12 avril 2026',
    title: 'iWiki \u2014 Encyclop\u00e9die des H\u00e9ros & Vilains',
    tag: 'major',
    changes: [
      { type: 'new', text: 'Nouvelle page iWiki accessible depuis la sidebar' },
      { type: 'new', text: 'Vitrine stylis\u00e9e H\u00e9ros/Vilains avec animations comic, particules et hover 3D' },
      { type: 'new', text: 'R\u00e9pertoire complet avec recherche et filtres (h\u00e9ros/vilain/tous)' },
      { type: 'new', text: 'Fiches d\u00e9taill\u00e9es : stats radar, pouvoirs, histoire, alli\u00e9s/ennemis' },
      { type: 'new', text: 'Gestion admin : cr\u00e9ation, modification, suppression, upload photo' },
    ],
  },
  {
    version: '3.6.0',
    date: '12 avril 2026',
    title: 'Temps r\u00e9el \u2014 Supabase Realtime',
    tag: 'minor',
    changes: [
      { type: 'new', text: 'Messages en temps r\u00e9el via WebSocket (remplacement du polling 8s)' },
      { type: 'new', text: 'Bandeau \u00ab Nouveaux posts \u00bb sur le feed quand d\u2019autres utilisateurs publient' },
      { type: 'new', text: 'Commentaires en direct sur la page de d\u00e9tail d\u2019un post' },
      { type: 'new', text: 'Composable r\u00e9utilisable useRealtimeSubscription pour les abonnements Supabase' },
      { type: 'improved', text: 'Polling r\u00e9duit \u00e0 30s en fallback (au lieu de 5-20s)' },
    ],
  },
  {
    version: '3.5.0',
    date: '11 avril 2026',
    title: 'Clustering carte & navigation filtres',
    tag: 'minor',
    changes: [
      { type: 'new', text: 'Les marqueurs proches se regroupent en bulles avec compteur (clustering spatial)' },
      { type: 'new', text: 'Au survol d\u2019un cluster, les marqueurs se d\u00e9ploient en \u00e9ventail anim\u00e9' },
      { type: 'new', text: 'Chaque filtre de cat\u00e9gorie affiche la liste des lieux au survol avec navigation directe' },
      { type: 'improved', text: 'Recalcul automatique des clusters au zoom et d\u00e9placement de la carte' },
    ],
  },
  {
    version: '3.4.0',
    date: '8 avril 2026',
    title: 'Carte vivante \u2014 Marqueurs anim\u00e9s, Heatmap & Zones',
    tag: 'minor',
    changes: [
      { type: 'new', text: 'Les marqueurs avec des posts r\u00e9cents pulsent proportionnellement \u00e0 l\u2019activit\u00e9 (3 niveaux d\u2019intensit\u00e9)' },
      { type: 'new', text: 'Heatmap d\u2019activit\u00e9 : couche de chaleur montrant les zones les plus actives (toggle dans la toolbar)' },
      { type: 'new', text: 'Zones admin : les admins peuvent dessiner des polygones sur la carte (safe, danger, neutre, contest\u00e9)' },
      { type: 'new', text: 'Panel de d\u00e9tail pour les zones avec nom, type et description' },
      { type: 'improved', text: 'Curseur crosshair en mode dessin de zone pour mieux visualiser le placement' },
    ],
  },
  {
    version: '3.3.1',
    date: '8 avril 2026',
    title: 'Inventaire — images custom & fix doublon',
    tag: 'patch',
    changes: [
      { type: 'new', text: 'Possibilit\u00e9 d\'ajouter une image personnalis\u00e9e sur chaque objet de l\'inventaire (toggle Emoji / Image)' },
      { type: 'improved', text: 'L\'image remplace l\'\u00e9moji sur la carte inventaire si pr\u00e9sente' },
      { type: 'fixed', text: 'Suppression du bouton doublon \u00ab Ajouter un objet \u00bb quand l\'inventaire est vide' },
    ],
  },
  {
    version: '3.3.0',
    date: '7 avril 2026',
    title: 'Posts sur la carte — badge & tooltip',
    tag: 'minor',
    changes: [
      { type: 'new', text: 'Un petit badge num\u00e9rique sur chaque lieu de la carte indique le nombre de posts rattach\u00e9s' },
      { type: 'new', text: 'Au survol du lieu, un tooltip affiche la liste des posts avec avatar, auteur, contenu et timestamp' },
      { type: 'new', text: 'Chaque post dans le tooltip est cliquable et redirige vers le d\u00e9tail du post' },
      { type: 'improved', text: '20 posts r\u00e9cents affich\u00e9s sur la carte (contre 5 avant)' },
      { type: 'improved', text: 'Interface carte plus propre : plus de photos de profil volantes, tout est int\u00e9gr\u00e9 au marqueur' },
      { type: 'new', text: 'Clic sur un lieu : les posts rattach\u00e9s s\'affichent dans le panel de d\u00e9tail \u00e0 droite' },
    ],
  },
  {
    version: '3.2.1',
    date: '7 avril 2026',
    title: 'Admin Banque — Overview compl\u00e8te',
    tag: 'patch',
    changes: [
      { type: 'new', text: 'Nouvel onglet Banque dans le panel Admin avec vue d\u2019ensemble compl\u00e8te' },
      { type: 'new', text: 'Statistiques : argent en circulation, nombre de comptes, solde moyen, plus riche, volume total des transactions' },
      { type: 'new', text: 'Tableau de tous les soldes avec recherche, tri (solde, nom), et nombre de transactions par profil' },
      { type: 'new', text: 'Historique des 100 derni\u00e8res transactions (exp\u00e9diteur, destinataire, montant, note, date)' },
      { type: 'new', text: 'Actions rapides : cr\u00e9diter/d\u00e9biter un compte directement depuis le tableau admin' },
      { type: 'improved', text: 'Le widget DM se masque automatiquement sur la page Messages' },
    ],
  },
  {
    version: '3.2.0',
    date: '7 avril 2026',
    title: 'Refonte Messages style X + fix notifications',
    tag: 'minor',
    changes: [
      { type: 'new', text: 'Page Messages en layout 2 colonnes : liste des conversations \u00e0 gauche, conversation active \u00e0 droite' },
      { type: 'new', text: 'Chaque conversation affiche le dernier message, le timestamp et un indicateur non-lu' },
      { type: 'new', text: 'Badge de messages non-lus par profil dans le switcher' },
      { type: 'improved', text: 'Les notifications et badges se mettent \u00e0 jour instantan\u00e9ment (optimistic updates)' },
      { type: 'improved', text: 'La sidebar \u00e9coute les changements de lecture pour rafra\u00eechir le badge imm\u00e9diatement' },
      { type: 'fixed', text: 'Correction du nom de table conversation_participants \u2192 conversation_members (erreur 404)' },
      { type: 'fixed', text: 'Les badges de notifications et messages se chargent correctement d\u00e8s le d\u00e9marrage' },
      { type: 'improved', text: 'Le widget messages flottant et l\u2019onglet Messages sont d\u00e9sormais synchronis\u00e9s en temps r\u00e9el' },
      { type: 'improved', text: 'Refonte compl\u00e8te de l\u2019ergonomie Messages : bulles plus grandes, input polish\u00e9 avec ic\u00f4nes SVG, header avec lien profil, scrollbar discr\u00e8te, placeholder et \u00e9tats vides soign\u00e9s' },
    ],
  },
  {
    version: '3.1.1',
    date: '6 avril 2026',
    title: 'Fix compteurs ghost & notifications',
    tag: 'hotfix',
    changes: [
      { type: 'fixed', text: 'Les compteurs de likes/commentaires/reposts ghost s\'affichent de nouveau correctement sur les posts' },
      { type: 'fixed', text: 'Les notifications n\'apparaissent plus en double dans la cloche (fix race condition realtime + contrainte unique DB)' },
      { type: 'fixed', text: 'Le badge messages non-lus ne compte plus les messages de conversations auxquelles on ne participe pas' },
    ],
  },
  {
    version: '3.1.0',
    date: '5 avril 2026',
    title: 'Mentions de lieux (<Lieu>)',
    tag: 'minor',
    changes: [
      { type: 'new', text: 'Mention de lieux dans les posts : tapez < pour ouvrir l\'autocompl\u00e9tion des lieux de la carte' },
      { type: 'new', text: 'Les mentions de lieux s\'affichent en dor\u00e9 avec un \u{1F4CD} et redirigent vers la carte au clic' },
      { type: 'new', text: 'Panel de d\u00e9tail sur la carte : section "Posts r\u00e9cents" avec les 5 derniers posts mentionnant le lieu' },
      { type: 'new', text: 'Navigation automatique vers un lieu depuis un lien de mention (centrage + s\u00e9lection)' },
      { type: 'improved', text: 'Le composant MentionInput g\u00e8re d\u00e9sormais deux modes : @ pour les utilisateurs, < pour les lieux' },
      { type: 'improved', text: 'Recherche de lieux instantan\u00e9e (filtrage client-side, pas de requ\u00eate serveur)' },
    ],
  },
  {
    version: '3.0.0',
    date: '5 avril 2026',
    title: 'iCHARACTER & iBANK',
    tag: 'major',
    changes: [
      { type: 'new', text: 'Onglet iCHARACTER : fiche compl\u00e8te avec photo, identit\u00e9 (nom, pr\u00e9nom, nationalit\u00e9, sexe, lieu/date de naissance)' },
      { type: 'new', text: '5 comp\u00e9tences : Charisme, Intelligence, Force, Vigueur, Mobilit\u00e9 (0-5)' },
      { type: 'new', text: 'Radar chart pentagone SVG avec 3 niveaux concentriques et animation' },
      { type: 'new', text: 'Inventaire d\'objets avec \u00e9mojis, nom, description et quantit\u00e9' },
      { type: 'new', text: 'Mode \u00e9dition pour le propri\u00e9taire, mode lecture pour les autres' },
      { type: 'new', text: 'Upload de photo personnage (bucket Supabase d\u00e9di\u00e9)' },
      { type: 'new', text: 'Onglet iBANK : compte en dollars ($) par profil avec solde affich\u00e9 en grand' },
      { type: 'new', text: 'Transfert d\u2019argent entre profils avec recherche de destinataire et note optionnelle' },
      { type: 'new', text: 'Historique des transactions color\u00e9 (vert = re\u00e7u, rouge = envoy\u00e9)' },
      { type: 'new', text: 'Section admin : cr\u00e9dit/d\u00e9bit libre sur n\u2019importe quel compte (MJ)' },
      { type: 'new', text: 'Transferts atomiques s\u00e9curis\u00e9s via RPC Supabase' },
      { type: 'new', text: 'Rate limiting sur les transferts (5 par minute)' },
      { type: 'new', text: 'Liens iCHARACTER et iBANK ajout\u00e9s dans la sidebar et le menu mobile' },
    ],
  },
  {
    version: '2.16.0',
    date: '4 avril 2026',
    title: 'Carte interactive d\'Allentown',
    tag: 'minor',
    changes: [
      { type: 'new', text: 'Carte interactive sombre de la ville d\'Allentown avec tuiles CartoDB Dark Matter' },
      { type: 'new', text: '10 cat\u00e9gories de lieux : R\u00e9sidence, \u00c9cole, Lieu cl\u00e9, QG, Zone dangereuse, Commerce, H\u00f4pital, Police, Repaire de vilain, Autre' },
      { type: 'new', text: 'Markers custom avec emojis, couleurs par cat\u00e9gorie et effet glow lumineux' },
      { type: 'new', text: 'Panel lat\u00e9ral de d\u00e9tail avec image, description et profil li\u00e9 cliquable' },
      { type: 'new', text: 'Mode ajout admin : cliquer sur la carte pour placer un nouveau lieu' },
      { type: 'new', text: 'Upload d\'images pour chaque lieu (bucket Supabase d\u00e9di\u00e9)' },
      { type: 'new', text: 'Liaison optionnelle d\'un lieu \u00e0 un personnage (@username)' },
      { type: 'new', text: 'Filtres par cat\u00e9gorie avec chips scrollables' },
      { type: 'new', text: 'Lien "Carte" dans la sidebar et le menu mobile' },
      { type: 'improved', text: 'Overlay vignette cin\u00e9matique et contr\u00f4les de zoom int\u00e9gr\u00e9s au th\u00e8me sombre' },
    ],
  },
  {
    version: '2.15.1',
    date: '4 avril 2026',
    title: 'Hero dans les posts cit\u00e9s + corrections',
    tag: 'patch',
    changes: [
      { type: 'new', text: 'Le style Hero (bordure anim\u00e9e, glow, badge \u00e9toile) s\'affiche aussi dans les posts et commentaires cit\u00e9s' },
      { type: 'improved', text: 'Les donn\u00e9es Hero (is_hero, couleurs) sont maintenant r\u00e9cup\u00e9r\u00e9es pour les auteurs de commentaires cit\u00e9s' },
      { type: 'fix', text: 'L\'enrichissement des posts originaux (reposts/citations) inclut d\u00e9sormais les champs Hero' },
    ],
  },
  {
    version: '2.15.0',
    date: '4 avril 2026',
    title: 'R\u00f4le Hero \u2014 posts super-highlight personnalisables',
    tag: 'minor',
    changes: [
      { type: 'new', text: 'Nouveau r\u00f4le "Hero" avec bordure anim\u00e9e d\u00e9grad\u00e9e, effet glow et fond teint\u00e9 sur les posts' },
      { type: 'new', text: 'Badge \u00e9toile dor\u00e9 \u00e0 c\u00f4t\u00e9 du nom des Heroes dans les posts et le feed' },
      { type: 'new', text: 'Nom d\'affichage en d\u00e9grad\u00e9 avec les couleurs personnalis\u00e9es du Hero' },
      { type: 'new', text: 'Personnalisation des couleurs Hero (primaire + secondaire) depuis les param\u00e8tres avec aper\u00e7u en direct' },
      { type: 'new', text: 'Badge "Hero" sur les profils avec banni\u00e8re color\u00e9e et halo lumineux autour de l\'avatar' },
      { type: 'new', text: 'Bouton toggle Hero dans le panel admin pour attribuer/retirer le r\u00f4le' },
      { type: 'new', text: 'Tag Hero visible dans la recherche de profils' },
    ],
  },
  {
    version: '2.14.0',
    date: '2 avril 2026',
    title: '@Mentions + notifications',
    tag: 'minor',
    changes: [
      { type: 'new', text: 'Mentionner quelqu\'un avec @username dans un post ou commentaire' },
      { type: 'new', text: 'Autocomplete en tapant @ — affiche les profils correspondants' },
      { type: 'new', text: 'Les @mentions sont cliquables et redirigent vers le profil' },
      { type: 'new', text: 'Notification envoyée à la personne mentionnée' },
      { type: 'new', text: 'Triggers SQL pour les notifications de likes, commentaires, reposts et mentions' },
      { type: 'fix', text: 'Correction des notifications qui n\'étaient jamais créées (triggers manquants)' },
    ],
  },
  {
    version: '2.13.0',
    date: '2 avril 2026',
    title: 'Compteurs virtuels + images DM principal',
    tag: 'minor',
    changes: [
      { type: 'new', text: 'Compteurs virtuels illimités (likes, commentaires, reposts) — l\'admin peut mettre des millions sans générer de données' },
      { type: 'new', text: 'Envoi et affichage d\'images dans l\'onglet principal des messages (pas seulement le widget)' },
      { type: 'improved', text: 'Le masquage de conversations persiste entre les sessions mais se réinitialise quand un nouveau message arrive' },
      { type: 'fix', text: 'Correction du chargement des conversations cassé par la requête conversation_hidden' },
    ],
  },
  {
    version: '2.12.0',
    date: '1 avril 2026',
    title: 'Masquage de conversations + images DM widget',
    tag: 'minor',
    changes: [
      { type: 'new', text: 'Bouton × au survol de chaque conversation pour la masquer (page Messages et widget flottant)' },
      { type: 'new', text: 'La conversation masquée disparaît de l\'interface sans être supprimée pour l\'autre personne' },
      { type: 'improved', text: 'Les images étaient déjà envoyables depuis le widget flottant — le bucket dm-images est maintenant documenté' },
    ],
  },
  {
    version: '2.11.0',
    date: '1 avril 2026',
    title: 'Suppression de messages DM',
    tag: 'minor',
    changes: [
      { type: 'new', text: 'Bouton supprimer visible au survol de ses propres messages' },
      { type: 'new', text: 'Les admins peuvent supprimer n\'importe quel message' },
      { type: 'improved', text: 'Suppression instantanée sans rechargement de la conversation' },
    ],
  },
  {
    version: '2.10.0',
    date: '1 avril 2026',
    title: 'Citations de posts et commentaires',
    tag: 'major',
    changes: [
      { type: 'new', text: 'Le bouton Repost est désormais un menu déroulant avec "Repost" et "Citer"' },
      { type: 'new', text: 'Citer un post ouvre un compositeur avec aperçu du post original intégré' },
      { type: 'new', text: 'Citer un commentaire depuis sa page de post intègre le commentaire dans un nouveau post' },
      { type: 'new', text: 'Les posts cités affichent un embed du post ou commentaire original, cliquable' },
      { type: 'new', text: 'Support des images dans les posts de citation' },
    ],
  },
  {
    version: '2.9.0',
    date: '1 avril 2026',
    title: 'Engagement Ghost (Admin)',
    tag: 'major',
    changes: [
      { type: 'new', text: 'Les admins peuvent booster artificiellement les likes, reposts et commentaires d\'un post (bouton ⚡)' },
      { type: 'new', text: 'Génération de faux profils américains aléatoires avec noms réalistes' },
      { type: 'new', text: '7 humeurs disponibles pour les faux commentaires : joyeux, en colère, triste, excité, choqué, indifférent, amoureux' },
      { type: 'new', text: 'Dataset de phrases authentiques par humeur en français' },
      { type: 'new', text: 'Les faux profils sont consultables via leur page profil dédiée' },
      { type: 'new', text: 'Bouton "Tout effacer" pour réinitialiser l\'engagement ghost d\'un post' },
      { type: 'improved', text: 'Les faux comptes apparaissent dans la liste des likes et les commentaires de façon indiscernable' },
    ],
  },
  {
    version: '2.8.0',
    date: '1 avril 2026',
    title: 'Images dans les commentaires',
    tag: 'minor',
    changes: [
      { type: 'new', text: 'Possibilité d\'ajouter une image (JPG, PNG, GIF, WebP) à un commentaire ou une réponse' },
      { type: 'new', text: 'Prévisualisation de l\'image avant envoi avec suppression possible' },
      { type: 'new', text: 'Affichage de l\'image dans le commentaire, cliquable pour ouvrir en grand' },
      { type: 'improved', text: 'Les commentaires peuvent désormais contenir uniquement une image (sans texte obligatoire)' },
    ],
  },
  {
    version: '2.7.0',
    date: '30 mars 2026',
    title: 'Tendances par hashtags & ajustements UI',
    tag: 'minor',
    changes: [
      { type: 'changed', text: 'Les tendances sont d\u00e9sormais bas\u00e9es sur les #hashtags au lieu de la fr\u00e9quence de mots' },
      { type: 'new', text: 'Liste des hashtags scrollable dans le panneau lat\u00e9ral (max 15 tendances)' },
      { type: 'improved', text: 'Hashtags affich\u00e9s en bleu accent avec compteur de posts' },
      { type: 'fixed', text: 'Widget DM repositionn\u00e9 pour ne plus chevaucher le panneau utilisateurs actifs' },
      { type: 'improved', text: 'Tendances inline sur mobile mises \u00e0 jour avec le syst\u00e8me hashtag' },
    ],
  },
  {
    version: '2.6.0',
    date: '30 mars 2026',
    title: 'Notifications multi-profils & filtres',
    tag: 'major',
    changes: [
      { type: 'new', text: 'Onglets par profil dans le panneau de notifications avec badge non-lus individuel' },
      { type: 'new', text: 'Filtres par type : Tout / Likes / Commentaires / Reposts' },
      { type: 'new', text: 'Indicateur du profil destinataire sur chaque notification (multi-comptes)' },
      { type: 'new', text: 'Ic\u00f4nes color\u00e9es par type : rouge (like), bleu (commentaire), vert (reply/repost)' },
      { type: 'new', text: 'Point bleu non-lu \u00e0 droite de chaque notification' },
      { type: 'improved', text: '"Tout lire" marque uniquement les notifications du profil s\u00e9lectionn\u00e9' },
      { type: 'improved', text: 'Design SVG pour la cloche + panneau \u00e9largi (400px) avec meilleur responsive mobile' },
      { type: 'new', text: 'Switcher de comptes ajout\u00e9 sur la navigation mobile' },
    ],
  },
  {
    version: '2.4.1',
    date: '29 mars 2026',
    title: 'Boutons d\'action modernisés',
    tag: 'patch',
    changes: [
      { type: 'improve', text: 'Nouveaux pictogrammes SVG pour les boutons Commenter, Repost et Like, avec animation de clic.' },
      { type: 'fix', text: 'Correction de l\'alignement de l\'icône cœur (like) pour éviter qu\'elle soit coupée à droite.' },
      { type: 'improve', text: 'Icône Repost du badge harmonisée avec celle du bouton.' },
    ],
  },
  {
    version: '2.4.0',
    date: '28 mars 2026',
    title: 'Certification Admin & Posts highlight\u00e9s',
    tag: 'minor',
    changes: [
      { type: 'new', text: 'Badge certifi\u00e9 bleu (checkmark) \u00e0 c\u00f4t\u00e9 du nom des admins dans chaque post' },
      { type: 'new', text: 'Nom des admins affich\u00e9 en couleur accent (bleu) dans les posts' },
      { type: 'new', text: 'Posts des admins mis en avant : bordure bleue \u00e0 gauche et fond l\u00e9g\u00e8rement teint\u00e9' },
    ],
  },
  {
    version: '2.3.0',
    date: '28 mars 2026',
    title: 'Bio & Visionneuse avatar',
    tag: 'minor',
    changes: [
      { type: 'new', text: 'Champ bio dans les param\u00e8tres du profil (160 caract\u00e8res max) avec compteur' },
      { type: 'new', text: 'Bio affich\u00e9e sur la page de profil sous le nom d\'utilisateur' },
      { type: 'new', text: 'Lightbox avatar : cliquez sur la photo de profil pour l\'afficher en grand (300px, circulaire)' },
      { type: 'improved', text: 'Animation d\'ouverture fluide avec backdrop blur sur la lightbox' },
    ],
  },
  {
    version: '2.2.0',
    date: '28 mars 2026',
    title: 'Recherche & Tendances',
    tag: 'major',
    changes: [
      { type: 'new', text: 'Page de recherche avec onglets Tout / Profils / Posts et recherche d\u00e9bounc\u00e9e' },
      { type: 'new', text: 'Mise en surbrillance des termes recherch\u00e9s dans les r\u00e9sultats' },
      { type: 'new', text: 'Panneau lat\u00e9ral droit : mots-cl\u00e9s tendances extraits des posts r\u00e9cents (7 jours)' },
      { type: 'new', text: 'Section utilisateurs les plus actifs de la semaine' },
      { type: 'new', text: 'Lien Recherche ajout\u00e9 dans la sidebar et la navigation mobile' },
      { type: 'improved', text: 'Layout 3 colonnes sur grand \u00e9cran : sidebar + contenu + tendances' },
      { type: 'fixed', text: 'Navigation entre tendances sans rechargement — watch sur le param\u00e8tre URL' },
      { type: 'improved', text: 'Tendances et utilisateurs actifs affich\u00e9s directement dans la page recherche sur mobile' },
    ],
  },
  {
    version: '2.1.0',
    date: '28 mars 2026',
    title: 'Sidebar navigation & Recadrage avatar',
    tag: 'major',
    changes: [
      { type: 'new', text: 'Barre lat\u00e9rale fixe avec navigation : Feed, Messages, Profil, Param\u00e8tres, Patch Notes, Admin' },
      { type: 'new', text: 'Navigation mobile en barre inf\u00e9rieure sur petits \u00e9crans' },
      { type: 'new', text: 'Switcher de profil int\u00e9gr\u00e9 dans la sidebar avec recherche' },
      { type: 'new', text: 'Badge compteur de messages non-lus dans la sidebar' },
      { type: 'new', text: 'Recadrage interactif de la photo de profil : zoom, d\u00e9placement, aper\u00e7u circulaire' },
      { type: 'improved', text: 'Header simplifi\u00e9 — navigation d\u00e9plac\u00e9e dans la sidebar' },
    ],
  },
  {
    version: '2.0.0',
    date: '28 mars 2026',
    title: 'Panel Administrateur',
    tag: 'major',
    changes: [
      { type: 'new', text: 'Dashboard avec statistiques globales : comptes, profils, posts, likes, commentaires, messages, reposts, conversations' },
      { type: 'new', text: 'Gestion des utilisateurs : liste compl\u00e8te, recherche, toggle admin, suppression de profils' },
      { type: 'new', text: 'Mod\u00e9ration des posts : parcourir, rechercher et supprimer n\'importe quel post' },
      { type: 'new', text: 'Surveillance des conversations : voir toutes les conversations priv\u00e9es et lire tous les messages' },
      { type: 'new', text: 'Mod\u00e9ration des commentaires : parcourir, rechercher et supprimer des commentaires' },
      { type: 'new', text: 'Fil d\'activit\u00e9 r\u00e9cente : derniers posts, commentaires et likes en temps r\u00e9el' },
      { type: 'new', text: 'Bans temporaires : 15min, 30min, 1h, 3h, 6h, 12h, 24h, 3j, 7j ou dur\u00e9e personnalis\u00e9e' },
      { type: 'new', text: 'Banni\u00e8re d\'avertissement pour les profils bannis — actions bloqu\u00e9es (posts, likes, commentaires, DMs)' },
      { type: 'security', text: 'Route prot\u00e9g\u00e9e par guard admin — acc\u00e8s refus\u00e9 aux non-admins' },
      { type: 'improved', text: 'Lien admin visible uniquement pour les admins dans le header' },
    ],
  },
  {
    version: '1.9.0',
    date: '28 mars 2026',
    title: 'Profil redesign\u00e9 style Twitter',
    tag: 'major',
    changes: [
      { type: 'new', text: 'Banni\u00e8re gradient en haut du profil avec avatar 120px en overlay' },
      { type: 'new', text: '4 onglets de contenu : Posts, Reposts, J\'aime, M\u00e9dias avec lazy-loading' },
      { type: 'new', text: 'Grille m\u00e9dia (3 colonnes) affichant toutes les images post\u00e9es par l\'utilisateur' },
      { type: 'new', text: 'Statistiques du profil : nombre de posts et de likes re\u00e7us' },
      { type: 'improved', text: 'Bouton DM int\u00e9gr\u00e9 directement sur le profil des autres utilisateurs' },
      { type: 'improved', text: 'Design responsive adapt\u00e9 mobile et desktop' },
    ],
  },
  {
    version: '1.8.0',
    date: '28 mars 2026',
    title: 'Notifications in-app & Discord',
    tag: 'major',
    changes: [
      { type: 'new', text: 'Cloche de notifications dans le header avec badge compteur de non-lues' },
      { type: 'new', text: 'Notifications automatiques pour : likes, commentaires, r\u00e9ponses aux commentaires, reposts' },
      { type: 'new', text: 'Panel d\u00e9roulant avec liste des notifications, avatar de l\'acteur et lien vers le post' },
      { type: 'new', text: 'Bouton "Tout lire" pour marquer toutes les notifications comme lues' },
      { type: 'new', text: 'Webhook Discord : chaque nouveau post est automatiquement envoy\u00e9 dans un salon Discord' },
      { type: 'improved', text: 'Triggers SQL serveur pour g\u00e9n\u00e9rer les notifications — aucune action c\u00f4t\u00e9 client' },
    ],
  },
  {
    version: '1.7.0',
    date: '28 mars 2026',
    title: 'Page Highlights & Timeline',
    tag: 'minor',
    changes: [
      { type: 'new', text: 'Nouvel onglet "Highlights" avec timeline visuelle des grandes fonctionnalit\u00e9s d\'iCAN' },
      { type: 'new', text: 'Design timeline altern\u00e9 gauche/droite avec cartes color\u00e9es, ic\u00f4nes et tags' },
      { type: 'improved', text: 'Navigation par onglets entre Highlights et Patch Notes' },
    ],
  },
  {
    version: '1.6.4',
    date: '28 mars 2026',
    title: 'Fix \u00e9cran bleu, cache & cr\u00e9ation de groupe',
    tag: 'hotfix',
    changes: [
      { type: 'fixed', text: 'L\'application se monte imm\u00e9diatement au lieu d\'attendre la fin de l\'initialisation auth \u2014 plus d\'\u00e9cran bleu vide au refresh' },
      { type: 'fixed', text: 'Timeout de s\u00e9curit\u00e9 de 5s sur l\'init auth pour d\u00e9bloquer l\'app si Supabase ne r\u00e9pond pas' },
      { type: 'fixed', text: 'Le router attend la fin de l\'init auth avant de d\u00e9cider de rediriger vers le login' },
      { type: 'fixed', text: 'Correction de l\'erreur 403 lors de la cr\u00e9ation d\'un groupe \u2014 utilisation d\'une fonction RPC atomique (create_group_conversation)' },
      { type: 'improved', text: 'Meta tags anti-cache pour \u00e9viter les versions p\u00e9rim\u00e9es apr\u00e8s d\u00e9ploiement' },
      { type: 'improved', text: 'Protection contre les d\u00e9connexions fant\u00f4mes : v\u00e9rification de la session avant logout automatique' },
    ],
  },
  {
    version: '1.6.3',
    date: '28 mars 2026',
    title: 'Fix persistance de session',
    tag: 'hotfix',
    changes: [
      { type: 'fixed', text: 'La session n\'est plus d\u00e9truite apr\u00e8s une p\u00e9riode d\'inactivit\u00e9 \u2014 le refresh token est pr\u00e9serv\u00e9 m\u00eame si le token d\'acc\u00e8s expire' },
      { type: 'improved', text: 'Supabase g\u00e8re maintenant le renouvellement automatique des tokens en arri\u00e8re-plan via onAuthStateChange' },
      { type: 'fixed', text: 'Suppression de l\'appel signOut() agressif qui d\u00e9truisait les sessions r\u00e9cup\u00e9rables lors d\'un \u00e9chec de refresh temporaire' },
    ],
  },
  {
    version: '1.6.2',
    date: '28 mars 2026',
    title: 'Fix erreurs 500 RLS groupes',
    tag: 'hotfix',
    changes: [
      { type: 'fixed', text: 'Correction des erreurs 500 sur les requ\u00eates messages caus\u00e9es par une r\u00e9cursion infinie dans les policies RLS des groupes' },
      { type: 'fixed', text: 'Nouvelle fonction helper my_conversation_ids() en SECURITY DEFINER pour \u00e9viter les boucles RLS' },
      { type: 'improved', text: 'Gestion d\'erreurs sur le polling DM \u2014 les erreurs r\u00e9seau ne bloquent plus l\'interface' },
    ],
  },
  {
    version: '1.6.1',
    date: '28 mars 2026',
    title: 'Fix likes multi-profils',
    tag: 'hotfix',
    changes: [
      { type: 'fixed', text: 'Les likes ne sont plus partag\u00e9s entre tous les profils d\'un m\u00eame compte \u2014 chaque profil a ses propres likes' },
      { type: 'fixed', text: 'Le compteur de likes se met correctement \u00e0 jour lors du unlike' },
      { type: 'fixed', text: 'Les likes de commentaires et les reposts respectent aussi le profil actif' },
    ],
  },
  {
    version: '1.6.0',
    date: '28 mars 2026',
    title: 'Groupes de discussion',
    tag: 'minor',
    changes: [
      { type: 'new', text: 'Conversations de groupe dans le widget DM \u2014 discutez \u00e0 plusieurs en temps r\u00e9el' },
      { type: 'new', text: 'Cr\u00e9ation de groupe : nom personnalis\u00e9, recherche et ajout de membres (minimum 2)' },
      { type: 'new', text: 'Affichage du nom de l\'exp\u00e9diteur dans les bulles de messages de groupe' },
      { type: 'new', text: 'Badge compteur de membres dans l\'en-t\u00eate des conversations de groupe' },
      { type: 'improved', text: 'Liste de conversations unifi\u00e9e : DMs et groupes tri\u00e9s par derni\u00e8re activit\u00e9' },
      { type: 'improved', text: 'Avatars de groupe distincts pour diff\u00e9rencier les conversations 1-\u00e0-1 des groupes' },
    ],
  },
  {
    version: '1.5.1',
    date: '28 mars 2026',
    title: 'Switcher profils am\u00e9lior\u00e9',
    tag: 'minor',
    changes: [
      { type: 'improved', text: 'Ajout d\u2019un scroll interne \u00e0 la liste des profils dans le switcher lorsque la hauteur d\u00e9passe 700px.' },
      { type: 'new', text: 'Ajout d\u2019une barre de recherche dynamique pour filtrer les profils par identifiant ou username dans le switcher.' },
      { type: 'improved', text: 'Scrollbar interne du switcher stylis\u00e9e pour correspondre \u00e0 l\u2019identit\u00e9 visuelle du site.' },
    ],
  },
  {
    version: '1.5.0',
    date: '28 mars 2026',
    title: 'Images en DM & Patch Notes',
    tag: 'minor',
    changes: [
      { type: 'new', text: 'Envoi d\'images dans les messages directs (JPG, PNG, GIF, WebP, max 5 Mo)' },
      { type: 'new', text: 'Pr\u00e9visualisation de l\'image avant envoi dans le widget DM' },
      { type: 'new', text: 'Page Patch Notes pour suivre les mises \u00e0 jour du site' },
      { type: 'improved', text: 'Aper\u00e7u "\ud83d\uddbc\ufe0f Image" dans la liste des conversations pour les messages sans texte' },
    ],
  },
  {
    version: '1.4.0',
    date: '28 mars 2026',
    title: 'S\u00e9curit\u00e9 & Qualit\u00e9 de vie',
    tag: 'minor',
    changes: [
      { type: 'new', text: 'Liste des personnes ayant lik\u00e9 un post (cliquable sur la page du post)' },
      { type: 'new', text: 'Bouton rafra\u00eechir d\u00e9plac\u00e9 en haut du feed avec header sticky "Accueil"' },
      { type: 'security', text: 'Rate limiting anti-spam : posts (5/min), commentaires (10/min), messages (20/min), likes (30/min)' },
      { type: 'security', text: 'Validation des uploads c\u00f4t\u00e9 store : type MIME + taille v\u00e9rifi\u00e9s' },
      { type: 'fixed', text: 'Persistance de connexion am\u00e9lior\u00e9e \u2014 la session survit au rafra\u00eechissement de page' },
    ],
  },
  {
    version: '1.3.0',
    date: '28 mars 2026',
    title: 'Widget DM & Images dans les posts',
    tag: 'major',
    changes: [
      { type: 'new', text: 'Widget DM flottant en bas \u00e0 gauche (style X/Twitter) \u2014 messagerie sans quitter la page' },
      { type: 'new', text: 'Recherche de conversations et cr\u00e9ation de nouvelles conversations depuis le widget' },
      { type: 'new', text: 'Publication d\'images avec les posts (bouton image dans le composeur)' },
      { type: 'new', text: 'Pr\u00e9visualisation avant publication avec suppression possible' },
      { type: 'new', text: 'Affichage des images dans le feed et les pages de d\u00e9tail' },
      { type: 'changed', text: 'Le lien "Messages" retir\u00e9 de la navigation \u2014 remplac\u00e9 par le widget' },
      { type: 'improved', text: 'Badge non-lus en temps r\u00e9el sur le widget DM' },
      { type: 'improved', text: 'Point bleu sur les conversations non lues' },
    ],
  },
  {
    version: '1.2.0',
    date: '28 mars 2026',
    title: 'Refonte des commentaires & reposts',
    tag: 'major',
    changes: [
      { type: 'new', text: 'Likes sur les commentaires (coeur rouge quand lik\u00e9)' },
      { type: 'new', text: 'R\u00e9ponses imbriqu\u00e9es aux commentaires avec fil visuel' },
      { type: 'new', text: 'Avatars et photos de profil sur chaque commentaire' },
      { type: 'new', text: 'Indicateur "En r\u00e9ponse \u00e0 @username" sur les r\u00e9ponses' },
      { type: 'new', text: 'Header "Commentaires" avec badge compteur' },
      { type: 'improved', text: 'Refonte compl\u00e8te de l\'affichage des reposts \u2014 contenu original visible' },
      { type: 'improved', text: 'Toggle repost (annulation possible, bouton vert quand repost\u00e9)' },
      { type: 'improved', text: 'Protection : impossible de reposter son propre post' },
      { type: 'fixed', text: 'Les compteurs de likes/reposts/commentaires pointent vers le post original' },
      { type: 'fixed', text: 'Le badge repost affiche correctement le nom du reposteur' },
    ],
  },
  {
    version: '1.1.0',
    date: '27 mars 2026',
    title: 'Multi-profils & Param\u00e8tres',
    tag: 'major',
    changes: [
      { type: 'new', text: 'Plusieurs profils par compte \u2014 switch entre alias pour poster sous diff\u00e9rentes identit\u00e9s' },
      { type: 'new', text: 'Page param\u00e8tres : gestion des profils, avatar, pseudo, nom d\'affichage' },
      { type: 'new', text: 'Upload de photo de profil (bucket Supabase Storage)' },
      { type: 'new', text: 'S\u00e9lecteur de profil dans le header avec dropdown' },
      { type: 'new', text: 'Composant UserAvatar r\u00e9utilisable (image ou initiale)' },
      { type: 'changed', text: 'Architecture BDD : profiles.owner_id (N:1) au lieu de profiles.id = auth.uid (1:1)' },
      { type: 'improved', text: 'Persistance du profil actif dans localStorage' },
    ],
  },
  {
    version: '1.0.0',
    date: '27 mars 2026',
    title: 'Lancement initial',
    tag: 'major',
    changes: [
      { type: 'new', text: 'Feed de posts avec cr\u00e9ation, suppression (auteur + admin)' },
      { type: 'new', text: 'Syst\u00e8me de likes (toggle)' },
      { type: 'new', text: 'Reposts' },
      { type: 'new', text: 'Commentaires sur les posts' },
      { type: 'new', text: 'Messages directs (DM) entre utilisateurs' },
      { type: 'new', text: 'Authentification par email/mot de passe (Supabase Auth)' },
      { type: 'new', text: 'Compte admin avec pouvoirs de mod\u00e9ration' },
      { type: 'new', text: 'Profils utilisateurs avec page d\u00e9di\u00e9e' },
      { type: 'new', text: 'D\u00e9ploiement automatique GitHub Pages via GitHub Actions' },
      { type: 'new', text: 'Th\u00e8me sombre inspir\u00e9 de Twitter/X' },
    ],
  },
]
</script>

<style scoped src="./PatchNotesView.css"></style>
